### ISSUE TITLE
Performance metric

### ISSUE THREAD

**Issue by folterj** [neka-nat/probreg#100]
Reading the readme, examples and documentation, it seems the return values are not specified for e.g.:
`probreg.bcpd.registration_bcpd()`
`probreg.cpd.registration_cpd()`

It is not clear if the functions return a meaningful performance metric, either a (sum/mean) distance or match rate. As no point matching information is returned, point distances cannot be calculated using the transform. So at the moment it seems the result can only be evaluated visually by plotting the points. Apologies if this is covered, but if not could this be added including corresponding documentation?

**Comment by neka-nat** [comment]
Thanks for pointing that out!
Documentation added.
Or you may want to look at examples.

**Comment by folterj** [comment]
Hi @neka-nat,
Thanks for following up on this so quickly.
The return value are now indeed in the documentation. However looking at the corresponding class, the values just say 'alias for field number #' (see below).
Regarding the examples, they don't seem to use the return values other than the transformation itself either.

```
classprobreg.cpd.MstepResult(transformation, sigma2, q)
Bases: tuple

property q
    Alias for field number 2
 
property sigma2
    Alias for field number 1
 
property transformation
    Alias for field number 0
```

**Comment by neka-nat** [comment]
I updated docs
https://probreg.readthedocs.io/en/latest/probreg.html#probreg.cpd.MstepResult
