### ISSUE TITLE
performance improvements for CPD

### ISSUE THREAD

**Issue by x1y9** [neka-nat/probreg#107]
change Line 70 in function expectation_step from

```
pmat = self.xp.stack([self.xp.sum(self.xp.square(target - ts), axis=1) for ts in t_source])
```

to

```
pmat = scipy.spatial.distance.cdist(t_source,target,"sqeuclidean")
```

can greatly improve the performance of the cpd algorithm. On my computer, it can be improved by 3 to 4 times.

**Comment by neka-nat** [comment]
Thank you!
I have reflected it in master!
