### ISSUE TITLE
L2-gmmreg goes wrong when translation exists

### ISSUE THREAD

**Issue by SILI1994** [neka-nat/probreg#11]
Hi! I have tested the l2-gmmreg code and I found that it performs weird if translation exits. Detailly, for a fixed rotation R, if the translation is set to 0, then all is fine. However, if the translation is not 0 then the estimated R would be far from the ground truth.

**Comment by neka-nat** [comment]
Hi,

I tried to execute the following code.

```
import numpy as np
import transformations as trans
from probreg import l2dist_regs
from probreg import callbacks
import utils

source, target = utils.prepare_source_and_target_rigid_3d('bunny.pcd', n_random=0, translation=np.array([0.1, 0.0, 0.0]))

cbs = [callbacks.Open3dVisualizerCallback(source, target)]
tf_param = l2dist_regs.registration_gmmreg(source, target, callbacks=cbs)
rot = trans.identity_matrix()
rot[:3, :3] = tf_param.rot
print("result: ", np.rad2deg(trans.euler_from_matrix(rot)),
      tf_param.scale, tf_param.t)
```
![Screenshot from 2019-11-15 10-13-02](https://user-images.githubusercontent.com/991515/68909479-b2d24b00-0791-11ea-9578-541312868617.png)

I don't think there is any strange behavior.
Can you send me the test code if possible?

**Comment by SILI1994** [comment]
Hi, here are my tests and please let me know if I make some mistakes here
```python
import copy
import numpy as np
import open3d as o3
from scipy.spatial.transform import Rotation as R
from probreg import l2dist_regs as l2
from probreg import cpd, gmmtree, filterreg


src = o3.read_point_cloud("bunny1.pcd")
tar = o3.read_point_cloud("bunny2.pcd")

# quaternion is (x,y,z,w) format 
print("ground-truth: ", [0.198129, 0.138726, 0.198129, 0.949866])

tf_param_l2 = l2.registration_gmmreg(src, tar)
print("l2: ", R.from_dcm(tf_param_l2.rot).as_quat())

tf_param_cpd, _, _ = cpd.registration_cpd(src, tar, maxiter=200, tol=1e-5)
print("cpd: ", R.from_dcm(tf_param_cpd.rot).as_quat())

tf_param_gmmtree, _ = gmmtree.registration_gmmtree(src, tar, maxiter=200, tol=1e-5) 
print("gmmtree: ", R.from_dcm(tf_param_gmmtree.rot).as_quat())

tf_param_f, _, _ = filterreg.registration_filterreg(src, tar, maxiter=200, tol=1e-5, min_sigma2=1e-10)
print("filter: ", R.from_dcm(tf_param_f.rot).as_quat())

# draw result of l2
result_l2 = copy.deepcopy(src)
result_l2.points = tf_param_l2.transform(result_l2.points)

src.paint_uniform_color([1, 0, 0])
tar.paint_uniform_color([0, 1, 0])
result_l2.paint_uniform_color([0, 0, 1])
o3.draw_geometries([src, tar, result_l2])

```

where bunny1.pcd is the origin, by rotating only I get bunny2.pcd and by rotating and translating I get bunny3.pcd and they are [here](https://github.com/neka-nat/probreg/files/3849539/test_data.zip).

I have tried several trails and it seems when the translation scale is small (somehow can be ignored and treated as noise), the algorithm would work. However, when it goes large, the registration would fail. And it seems the same problem also happens to GMMReg.  


**Failure case of L2-gmmreg by aligning bunny1.pcd and bunny2.pcd:**. The estimated rotation is pure identity.
![fail](https://user-images.githubusercontent.com/23044775/68912535-c08cce00-079b-11ea-9e3c-7bcb474b7f04.png)

**Success case of L2-gmmreg by aligning bunny1.pcd and bunny3.pcd:**
![success](https://user-images.githubusercontent.com/23044775/68912890-d353d280-079c-11ea-9968-d871c2b7f0f8.png)

**Comment by neka-nat** [comment]
In general, these algorithms differ from global registration and require initial values close to the solution.
Especially for gmmreg and gmmtree, the calculation of Gaussian distribution is 0 for point groups that are too far apart, so the solution cannot be obtained well.
To solve these problems, it seems necessary to align the centers of the point clouds in advance.

```py
import copy
import numpy as np
import open3d as o3
from scipy.spatial.transform import Rotation as R
from probreg import l2dist_regs as l2

src = o3.read_point_cloud("test_data/bunny1.pcd")
tar = o3.read_point_cloud("test_data/bunny2.pcd")
nrm_src = o3.PointCloud()
nrm_tar = o3.PointCloud()

nrm_src.points = o3.Vector3dVector(np.array(src.points) - np.array(src.points).mean(axis=0))
nrm_tar.points = o3.Vector3dVector(np.array(tar.points) - np.array(tar.points).mean(axis=0))

# quaternion is (x,y,z,w) format 
print("ground-truth: ", [0.198129, 0.138726, 0.198129, 0.949866])

tf_param_l2 = l2.registration_svr(nrm_src, nrm_tar)
print("l2: ", R.from_dcm(tf_param_l2.rot).as_quat())

# draw result of l2
result_l2 = copy.deepcopy(nrm_src)
result_l2.points = tf_param_l2.transform(result_l2.points)

nrm_src.paint_uniform_color([1, 0, 0])
nrm_tar.paint_uniform_color([0, 1, 0])
result_l2.paint_uniform_color([0, 0, 1])
o3.draw_geometries([nrm_src, nrm_tar, result_l2])
```

![Screenshot from 2019-11-15 13-39-07](https://user-images.githubusercontent.com/991515/68917582-4fa2e180-07ae-11ea-8b88-67961b1d00de.png)
