### ISSUE TITLE
GMM-Tree Code.

### ISSUE THREAD

**Issue by Liansheng-Wang** [neka-nat/probreg#110]
https://github.com/neka-nat/probreg/blob/master/probreg/cc/gmmtree.cc#L47
const auto idxs = (points.rows() * Vector::Random(max_tree_level * N_NODE)).array().abs().cast<Integer>();
The number of rows in idxs is max_tree_level * N_NODE.
But in https://github.com/neka-nat/probreg/blob/master/probreg/cc/gmmtree.cc#L49 and https://github.com/neka-nat/probreg/blob/master/probreg/cc/gmmtree.cc#L51, The maximum index of idxs is std::pow(N_NODE, max_tree_level).

**Comment by neka-nat** [comment]
Thanks!
I have fixed it.
