### ISSUE TITLE
[BUG] Error encountered using registration_cpd when using cuda

### ISSUE THREAD

**Issue by batu1579** [neka-nat/probreg#111]
Hi @neka-nat :

I encountered some errors when using cuda:

1. Errors occur when I use cuda and visual callbacks together
    ```
    RuntimeError: Unable to cast Python instance of type <class 'cupy.ndarray'> to C++ type '?' (#define PYBIND11_DETAILED_ERROR_MESSAGES or compile in debug mode for details)
    ```
2. An error occurs when I use cuda and tf_type_name="affine" at the same time

For the first question, the specific code associated with the error is here:

https://github.com/neka-nat/probreg/blob/c51d08628b7f50ca08ece97ba90227cd719c482e/probreg/transformation.py#L23-L26

I find that cupy.ndarray needs to be converted to numpy.ndarray to be properly received by array_type. Like this:

```python
    def transform(self, points, array_type=o3.utility.Vector3dVector):
        if isinstance(points, array_type):
            _array_after_transform = self._transform(self.xp.asarray(points)

            if isinstance(cupy.ndarray, _array_after_transform):
                _array_after_transform = _array_after_transform.get()

            return array_type(_array_after_transform)
        return self._transform(points)
```

As for the second question, the relevant code is here:

https://github.com/neka-nat/probreg/blob/c51d08628b7f50ca08ece97ba90227cd719c482e/probreg/cpd.py#L244

I noticed that an xp parameter was missing when I passed the parameter, causing xp in the transform object to become the default numpy module instead of the same cupy as the external one

Fixing it is as simple as adding the missing parameters, like this:

```python
return MstepResult(tf.AffineTransformation(b, t, xp=xp), sigma2, q)
```

May this library get better and better

**Comment by batu1579** [comment]
The current version of my simple fix is as follows:

```python
from typing import TypeAlias

import probreg
import numpy.typing as numpy_typing
import cupy.typing as cupy_typing

# Patch the probpreg.Transformation classes
UnionArrayT: TypeAlias = cupy.ndarray | numpy.ndarray


def convert_to_numpy(x: UnionArrayT) -> numpy.ndarray:
    return x.get() if isinstance(x, cupy.ndarray) else x  # pyright: ignore


def _patch_transform(
    transformation_class: type[probreg.transformation.Transformation],
) -> None:
    original_transform = transformation_class._transform

    def _patched_transform(
        self: probreg.transformation.Transformation,
        points: numpy_typing.ArrayLike | cupy_typing.ArrayLike,
    ) -> numpy.ndarray:
        return convert_to_numpy(original_transform(self, points))

    transformation_class._transform = _patched_transform


_patch_transform(probreg.transformation.RigidTransformation)
_patch_transform(probreg.transformation.AffineTransformation)
_patch_transform(probreg.transformation.NonRigidTransformation)
```

**Comment by neka-nat** [comment]
Thanks!
I have fixed it.
