### ISSUE TITLE
ImportError: cannot import name '_math' from partially initialized module 'probreg' (most likely due to a circular import) (/home/optics/file/shp/probreg-master/probreg/__init__.py)

### ISSUE THREAD

**Issue by sunhoupeng** [neka-nat/probreg#113]
![2024-05-20 09-13-17 的屏幕截图](https://github.com/neka-nat/probreg/assets/73348417/5d9bea4d-82fe-4c6b-947e-22bbf37a487a)
ImportError: cannot import name '_math' from partially initialized module 'probreg' (most likely due to a circular import) (/home/optics/file/shp/probreg-master/probreg/__init__.py)

**Comment by neka-nat** [comment]
Please refer these issues.

#4 
#27 
#64 
#84 
#101

**Comment by sunhoupeng** [comment]
thanks

**Comment by sunhoupeng** [comment]
thanks



---Original---
From: "Shirokuma (k ***@***.***&gt;
Date: Mon, May 20, 2024 10:28 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [neka-nat/probreg] ImportError: cannot import name '_math' frompartially initialized module 'probreg' (most likely due to a circular import)(/home/optics/file/shp/probreg-master/probreg/__init__.py) (Issue #113)




 
Please refer these issues.
 
#4
 #27
 #64
 #84
 #101
