### ISSUE TITLE
problem with install / open3d 0.8.0

### ISSUE THREAD

**Issue by argosvr** [neka-nat/probreg#12]
I'm trying to install probreg under my env ...
I tried the git method but the setup.py script is looking for the 0.7.0 open3d package..
the pip version install open3d 0.7.0 (I have already the 0.8.0 version and installed..
Then what is the best way to install probreg ?
I think it is really what is missing to Open3d which has no robust icp method.. then thank you for your work !

**Comment by neka-nat** [comment]
Hi @argosvr ,

Thank you for reporting.
I tried to install only open3d in my environment, ubuntu18.04 python3.6.

```
pip install open3d-python -U
```

And then, I checked the version.

```
python
>>> import open3d
>>> open3d.__version__
'0.7.0.0'
```
Depending on the environment, the version0.8.0 may not be installed.
Do you know how to install the version 0.8.0 using pip?

**Comment by argosvr** [comment]
hello... thanks..
my version installed was open3d 0.8.0 and my virtual env under conda is python 37.7 with ubuntu 18.04...
The problem is for me that the syntax changed from the 0.7.0 on which your code was based and 0.8.0 (0.9.0 now)...
Thanks a lot for your work !

**Comment by neka-nat** [comment]
The latest version of git, not pip, supports 0.8.0.
Please try installing from git.

```
git clone https://github.com/neka-nat/probreg.git --recursive
cd probreg
pip install -e .
```

**Comment by argosvr** [comment]
thanks for your answer.. I tested your solution but it still collects the open3d 0.7.0 version and install it over the version installed (the 0.8.0 in my case) and then the rest of my code working with version 0.8.0 does not work anymore... A part of your code is still using the syntax used by open3d 0.7.0..

**Comment by neka-nat** [comment]
Thank you for reporting.
Could you send me the actual error details?
I will fix it.

**Comment by neka-nat** [comment]
The latest master branch supports open3d 0.9.
Please try it.

**Comment by argosvr** [comment]
great !!! thanks a lot ! I will test it..

**Comment by neka-nat** [comment]
Did you try it?
