### ISSUE TITLE
Can't compile over linux and mac 

### ISSUE THREAD

**Issue by tdimry** [neka-nat/probreg#16]
Hi,

I'm using linux with ubuntu 16.04.12 and mac with macOs Catalina 10.15.2,
and I get the error below when trying to compile:
'-Wstrict-prototypes' is valid for C/ObjC but not for C++
both from source and using pip.
Can you please help?

Thanks,
Tal

**Comment by tdimry** [comment]
Just noted that the error is actually : pybind11/eigen.h: No such file or directory
Here is the log:

    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/anaconda3/envs/denv36/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/ubuntu/data/best_buddies_registration/probreg/setup.py'"'"'; __file__='"'"'/home/ubuntu/data/best_buddies_registration/probreg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/ubuntu/data/best_buddies_registration/probreg/
    Complete output (33 lines):
    Continuing your build using OpenMP...
    
    Found Eigen version 3.3.90 in: third_party/eigen
    Found Eigen version 3.3.90 in: third_party/eigen
    Found Eigen version 3.3.90 in: third_party/eigen
    Found Eigen version 3.3.90 in: third_party/eigen
    Found Eigen version 3.3.90 in: third_party/eigen
    Found Eigen version 3.3.90 in: third_party/eigen
    running develop
    running egg_info
    writing probreg.egg-info/PKG-INFO
    writing dependency_links to probreg.egg-info/dependency_links.txt
    writing requirements to probreg.egg-info/requires.txt
    writing top-level names to probreg.egg-info/top_level.txt
    reading manifest file 'probreg.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'probreg.egg-info/SOURCES.txt'
    running build_ext
    creating tmp
    gcc -pthread -B /home/ubuntu/anaconda3/envs/denv36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ubuntu/anaconda3/envs/denv36/include/python3.6m -c /tmp/tmpdmutdy2m.cpp -o tmp/tmpdmutdy2m.o -std=c++14
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    gcc -pthread -B /home/ubuntu/anaconda3/envs/denv36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ubuntu/anaconda3/envs/denv36/include/python3.6m -c /tmp/tmp754tyi13.cpp -o tmp/tmp754tyi13.o -fvisibility=hidden
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    building 'probreg._ifgt' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/probreg
    creating build/temp.linux-x86_64-3.6/probreg/cc
    gcc -pthread -B /home/ubuntu/anaconda3/envs/denv36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ubuntu/anaconda3/envs/denv36/include -I/home/ubuntu/anaconda3/envs/denv36/include -Ithird_party/eigen -I/home/ubuntu/anaconda3/envs/denv36/include/python3.6m -c probreg/cc/ifgt_py.cc -o build/temp.linux-x86_64-3.6/probreg/cc/ifgt_py.o -DVERSION_INFO="0.1.8" -std=c++14 -fopenmp -fvisibility=hidden
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    probreg/cc/ifgt_py.cc:1:28: fatal error: pybind11/eigen.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ubuntu/anaconda3/envs/denv36/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/ubuntu/data/best_buddies_registration/probreg/setup.py'"'"'; __file__='"'"'/home/ubuntu/data/best_buddies_registration/probreg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by neka-nat** [comment]
Hi,
Thank you for reporting.
I don't know the cause...
Please try to install pybind11 first, after that install probreg.

```
pip install pybind11
pip install probreg
```

**Comment by neka-nat** [comment]
It seems that installation support from anaconda is necessary.
