### ISSUE TITLE
Return error when I'm running

### ISSUE THREAD

**Issue by mohamadmarjani97** [neka-nat/probreg#17]

**Comment by neka-nat** [comment]
Is the bunny file properly loaded?

**Comment by mohamadmarjani97** [comment]
thanks Ii solved bud I get new error:
"ValueError: too many values to unpack (expected 2)" in line: tf_param, _,= cpd.registration_cpd(source, target)
do you know why this occur?

**Comment by neka-nat** [comment]
The first is a typo. Underline is missing.
```
tf_param, _,= cpd.registration_cpd(source, target) -> tf_param, _, _ = cpd.registration_cpd(source, target)
```
Second, the pcd file is too large and runs out of memory.
Please try reducing the number of points.

**Comment by mohamadmarjani97** [comment]
thanks so much. it was so amazing.
did you Implement other algorithm such as CPD in this library to use for example SVR, GMMTree and other?

**Comment by neka-nat** [comment]
Examples of each algorithm are in the following directory.
https://github.com/neka-nat/probreg/tree/master/examples
