### ISSUE TITLE
Non rigid transformation of mesh to point clouds?

### ISSUE THREAD

**Issue by Hippogriff** [neka-nat/probreg#18]
Does your package support non rigid transformation of mesh vertices to point cloud such that deformation is as rigid as possible?

**Comment by neka-nat** [comment]
Thank for suggestion.
Do you mean the following type of deformation model?
http://www.cs.tau.ac.il/~dcor/online_papers/papers/arap.pdf
I'm not considering supporting this method, but I want to support skinning using dual quaterninon.
https://www.cs.utah.edu/~ladislav/kavan07skinning/kavan07skinning.pdf

**Comment by Hippogriff** [comment]
I was thinking about this:
https://gravis.dmi.unibas.ch/publications/2007/CVPR07_Amberg.pdf
