### ISSUE TITLE
supply w parameter to filterreg

### ISSUE THREAD

**Issue by cmatija** [neka-nat/probreg#20]
Hi @neka-nat 

Thank you so much for this great toolbox! As far as I can see right now, there is no clear way to supply the w parameter when using filterreg. Adding w=0 to the arguments of filterreg.registration_filterreg, and passing the w in frg.registration() should do the trick. or did I miss something?

**Comment by neka-nat** [comment]
Hi @cmatija ,

Thank you for reporting.
I added the parameter "w" in `filterreg.registration_filterreg`.
You can use the updated function from the current master branch.
