### ISSUE TITLE
BCPD registration

### ISSUE THREAD

**Issue by KasiaSprawka** [neka-nat/probreg#28]
Hi @neka-nat, 

I am trying to register two 3d body models using bcpd algorithm, but I keep getting "SVD did not converge" error. Any ideas what I might be doing wrong?

Any help would be appreciated

**Comment by neka-nat** [comment]
Hi @KasiaSprawka ,

Thank you for reporting.
Currently, BCPD implementation does not contain convergence judgments, which causes such problems.
I am addressing that issue, so please wait.

**Comment by neka-nat** [comment]
I added a convergence condition to bcpd in the latest master.
