### ISSUE TITLE
KeyError: <class 'numpy.object_'> when using cupy

### ISSUE THREAD

**Issue by flugenheimer** [neka-nat/probreg#29]
Hi 
im getting the error 
KeyError: <class 'numpy.object_'>

when using cuda like your example: 
https://github.com/neka-nat/probreg/blob/master/examples/cpd_affine3d_cuda.py

it seems to be this part in the AffineCPD class: 
    def _transform(self, points):
        return self.xp.dot(points, self.b.T) + self.t

for some reason self.xp if cupy in the first iteration of registration function in cpd.py, but in the second iteration it changes to numpy, making it crash with the error as the array is cupy.

**Comment by neka-nat** [comment]
Hi @flugenheimer ,

Thank you for your reporting.
Can you tell me which version of probreg you use?

**Comment by flugenheimer** [comment]
@neka-nat it is version 0.2.3

**Comment by neka-nat** [comment]
Thank you!
I tried running the example script in my environment and it worked fine.

```
$ python cpd_affine3d_cuda.py 
geometry::PointCloud with 6821 points.
geometry::PointCloud with 7085 points.
time:  34.19987106323242
result:  [[ 9.51215198e-01  2.30045788e-02  7.79389406e-02]
 [-3.85000760e-04  1.01914326e+00  2.08745487e-03]
 [-1.19703883e-03  2.00628882e-03  1.03108464e+00]] [-92.60922167  -2.16612495 -39.74096545]
```
Can you send me all the error messages, including the trace, please?

**Comment by flugenheimer** [comment]
Hmm strange now I can not reproduce the error anymore now I am just getting: 
'Segmentation fault (core dumped)'

I have tried uninstalling probreg and cupy and installing again. and running in the terminal using: python3 cpd_affine3d_cuda.py and also in Spyder IDE

I have CUDA 10 installed and nvidia driver 410.129
