### ISSUE TITLE
Question about the results

### ISSUE THREAD

**Issue by rafaellaspy** [neka-nat/probreg#3]
Hi,
This is not an issue I'm facing.. But I'm wondering what exactly are the printed results in filterreg_rigid.py file under the examples folder, especially what is the tf_param.t ?

**Comment by neka-nat** [comment]
Hi,
Thank you for the question.
tf_param represents translation and rotation in 3D space.
tf_param has the following three members.
* `rot`: Rotation matrix (3x3 array)
* `t`: Translation vector (3 array)
* `scale`: Scaling (scalar)

**Comment by rafaellaspy** [comment]
Thank you!
