### ISSUE TITLE
_maximization_step in  DeformableKinematicFilterReg

### ISSUE THREAD

**Issue by cmatija** [neka-nat/probreg#30]
Hi @neka-nat 

If I may, I just wanted to quickly ask about the maximization_step function in the  DeformableKinematicFilterReg class. As I see, you are, within each maximization step, itself performing multiple iterations, where in each one you average the neighboring dual quaternions. Can you perhaps give me a reference or something where this type of optimization is described? I am currently trying to implement something resempling DynamicFusion, however I have nowhere found actual code of the optimization itself, so I was wondering :)

Cheers!

**Comment by neka-nat** [comment]
Hi @cmatija ,

Are you referring to the following part?

```py
x[idx] = (w[0] * q0 + w[1] * q1).transform_point(t_source[idx])
```

It's "Dual quaternion blending".
 http://www.cs.jhu.edu/~misha/ReadingSeminar/Papers/Kavan07.pdf

**Comment by cmatija** [comment]
thanks for coming back to me!

No, I meant the entire part in lines 217-240. you have `maxiter` iterations of expectation/maximization steps, but within a maximization step, you again loop for `maxiter` iterations. Naively, I would have thought that, since the jacobian is already computed using the fact that every node has the average of neighboring dual quaternions, it wouldn't be necessary to iterate the way you do within the maximization step, so I'm trying to find the flaw in my own reasoning :)

**Comment by neka-nat** [comment]
Your point is correct.
The loop was probably embedded for debugging.
I've confirmed that example works even with maxiter set to 1.
I also pushed the loop removal to master.
Thank you!

**Comment by neka-nat** [comment]
Thank you for the suggestion.
According to chapter 5 of the original paper, the parameter update is as follows:

dth = -A^(-1) * b

Since the amount of movement obtained by calculating the inverse matrix is dth, it must be iterated and integrated.

**Comment by cmatija** [comment]
yes, there is a need for the iteration, but I was under the impression that this iteration is done in lines 119-135. but now you have two iterations, the one in 119-135, _and_ the one in _maximization_step, so overall max_iter * max_iter iterations in total performed within the _maximization_step for DeformableKinematicFilterReg.

**Comment by neka-nat** [comment]
Each loop has a different meaning, so we need two loops.
The `registration` function's loop is a convergence loop for the EM algorithm.
whereas the loop of the `_maximization_step` function is defined by the Gauss Newton method and
it is a loop to find the minimum sum of residuals.
