### ISSUE TITLE
How to visualize the cpd_nonrigid3d_cuda result with open3d.visualization?

### ISSUE THREAD

**Issue by 1939938853** [neka-nat/probreg#31]
Hello,

I want to visualize the nonrigid registration result, source, target, "transformed". Is it possible? How to do it with open3d.visualization?

**Comment by neka-nat** [comment]
Hi @1939938853,

Thank you for reporting.
I added visualization to the nonrigid3d_cuda example.

https://github.com/neka-nat/probreg/blob/master/examples/cpd_nonrigid3d_cuda.py
