### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by sandwich25** [neka-nat/probreg#33]
Help, I'm getting this error every time I run the cpd_nonrigid3d_cuda.py
<img width="781" alt="1" src="https://user-images.githubusercontent.com/69758962/91662234-6f7c7980-eb24-11ea-903c-7ae6a99d33ed.PNG">

thanks in advance!

**Comment by neka-nat** [comment]
Hi @sandwich25 ,

Thanks for reporting this issue!
The following issue may be helpful.
https://github.com/fbpic/fbpic/issues/371
