### ISSUE TITLE
Initial estimation of sigma2 fails for FilterReg

### ISSUE THREAD

**Issue by drlight-code** [neka-nat/probreg#36]
I am experimenting with probreg for LiDAR scan registration. The scans are from successive UAV measurements and are pre-registered quite well at the start. Using CPD I get an expected result, however using the FilterReg registration the transformation converges to a wrong minimum. For the visualization I use the same callback for both methods in the Open3D viewer (python). It applies the transform that is passed into the callback to the source pointcloud and displays transformed source (green) and target (blue). I use the master branch of both Open3D and probreg. I attached an ascii PLY model of the two point sets. Thank you for any advice!

![cpd](https://user-images.githubusercontent.com/6815246/92695569-edbcf500-f348-11ea-93ec-f7d4c30c7d4e.gif)

![filterreg](https://user-images.githubusercontent.com/6815246/92695574-eeee2200-f348-11ea-96bf-eb9306670927.gif)

[frames.zip](https://github.com/neka-nat/probreg/files/5199924/frames.zip)

**Comment by neka-nat** [comment]
Hi @drlight-code ,

Thank you for the feedback.
I also try the following code using the attached data.

```py
import numpy as np
import transformations as trans
from probreg import filterreg
from probreg import callbacks
from probreg import math_utils as mu
import open3d as o3

sdata = np.loadtxt("frames/frame00000.txt")
tdata = np.loadtxt("frames/frame00001.txt")

def estimate_normals(pcd, params):
    pcd.estimate_normals(search_param=params)
    pcd.orient_normals_to_align_with_direction()

source = o3.geometry.PointCloud()
source.points = o3.utility.Vector3dVector(sdata)
target = o3.geometry.PointCloud()
target.points = o3.utility.Vector3dVector(tdata)
estimate_normals(target, o3.geometry.KDTreeSearchParamHybrid(radius=0.5, max_nn=50))

cbs = [callbacks.Open3dVisualizerCallback(source, target)]
objective_type = 'pt2pt'
tf_param, _, _ = filterreg.registration_filterreg(source, target,
                                                  #target_normals=np.asarray(target.normals),
                                                  objective_type=objective_type,
                                                  sigma2=1.0,
                                                  callbacks=cbs)
rot = trans.identity_matrix()
rot[:3, :3] = tf_param.rot
print("result: ", np.rad2deg(trans.euler_from_matrix(rot)),
      tf_param.scale, tf_param.t)
```

I don't know the cause, but I needed to adjust the parameters.
In this case, I set `sigma2=1`.

![pt2pt](https://user-images.githubusercontent.com/991515/92716954-787a1000-f39a-11ea-8e80-d5ddebf7b8c5.png)

**Comment by drlight-code** [comment]
Hi, setting the sigma explicitly works for me too. I have to read your paper more closely to better understand its implications and a reasonable initialization value for it. Thanks so much!

**Comment by drlight-code** [comment]
I am reopening this in case you want to look into the initial estimation of the sigma2. Thanks again for your support.
