### ISSUE TITLE
Update of sigma2 fails for FilterReg

### ISSUE THREAD

**Issue by drlight-code** [neka-nat/probreg#37]
As stated in #36, the initial estimation for the sigma2 parameter fails with the point clouds posted there. Additionally, updating the sigma during the inference fails. If is set `sigma2=1.0` the algorithm converges, however if I additionally set `update_sigma2=True` it fails to converge altogether and performs large transformation updates (mostly rotation) in each step, as seen in the image below.

![filterreg-updatesigma](https://user-images.githubusercontent.com/6815246/92720801-70ec4400-f365-11ea-9ee8-1a843d28cd8c.gif)

**Comment by neka-nat** [comment]
I haven't implemented it, but I have the following method.
When sigma2 is given None, sigma2 is initialized by the following function.

```py
sigma2 = math_utils.squared_kernel_sum(source, target)
```

You can then estimate min_sigma2 from sigma2.

```py
min_sigma2 = k * sigma2
```

The constant `k` needs to be determined.
