### ISSUE TITLE
CPD doesn't modify point cloud

### ISSUE THREAD

**Issue by Nikhil-Shenoy** [neka-nat/probreg#39]
I'm trying to align two 3D point clouds where I have the correspondences using non-rigid CPD. The optimizer shows that the loss is decreasing, but no deformation actually occurs. Both point clouds stay in the same place that they were initialized to. To test, I centered and aligned the point clouds and just modified the scale of one, then ran the CPD, but I still encountered the same issue. Is there anything I need to modify for one point cloud to deform to the other based on the correspondences?

This is my code:

`
    import copy
    import numpy as np
    import open3d as o3d
    from probreg import cpd, l2dist_regs, bcpd
    import sys
    import pdb
    import logging

    log = logging.getLogger('probreg')
    log.setLevel(logging.DEBUG)

    # Load the data
    
    pcd1_filename = "pcd1_centered.pcd"
    pcd2_filename = "pcd2_aligned.pcd"

    pcd1 = o3d.io.read_point_cloud(pcd1_filename)
    pcd2 = o3d.io.read_point_cloud(pcd2_filename)

    pcd2_points = np.asarray(pcd2.points)
    pcd2.points = o3d.utility.Vector3dVector(pcd2_points * 0.5)

    # compute cpd registration
    transform_type = 'nonrigid'
    tf_param, _, _ = cpd.registration_cpd(pcd2, pcd1, tf_type_name=transform_type)
    result = copy.deepcopy(pcd2)
    result.points = tf_param.transform(result.points)

    # draw result
    pcd1.paint_uniform_color([1, 0, 0])
    pcd2.paint_uniform_color(0, 1, 0])
    result.paint_uniform_color([0, 0, 1])
    o3d.visualization.draw_geometries([pcd1, result])

`

And this is the result that I get out from the scale test. This is exactly how I initialized the clouds; red is initial position of pcd1, green is initial position of pcd2, and blue is the result. The blue and green are overlapping:

![image](https://user-images.githubusercontent.com/5149854/93207679-50d3d080-f729-11ea-9ec4-66ba9d2aa384.png)

**Comment by neka-nat** [comment]
Hi @Nikhil-Shenoy 

Thank you for trying it out.
Can I get the point cloud data?
I'll check it out too.

**Comment by Nikhil-Shenoy** [comment]
[pcd_data.zip](https://github.com/neka-nat/probreg/files/5225128/pcd_data.zip)

@neka-nat Here's the data. The library looks really great by the way.

**Comment by neka-nat** [comment]
Thanks for the data.
I set `lmd=1.0e-5` to weaken the regularization, 
because if the initial values were far apart, the regularization would be stronger.
I've attached the code I tried and the results.

```py
import numpy as np
import open3d as o3d
from probreg import cpd
from probreg import callbacks
import logging

log = logging.getLogger('probreg')
log.setLevel(logging.DEBUG)

# Load the data

pcd1_filename = "pcd_data/pcd1_centered.pcd"
pcd2_filename = "pcd_data/pcd2_aligned.pcd"

pcd1 = o3d.io.read_point_cloud(pcd1_filename)
pcd2 = o3d.io.read_point_cloud(pcd2_filename)

pcd2_points = np.asarray(pcd2.points)
pcd2.points = o3d.utility.Vector3dVector(pcd2_points * 0.5)

# compute cpd registration
cbs = [callbacks.Open3dVisualizerCallback(pcd2, pcd1)]
tf_param, _, _ = cpd.registration_cpd(pcd2, pcd1, 'nonrigid',
                                      callbacks=cbs, lmd=1.0e-5)
```

![out](https://user-images.githubusercontent.com/991515/93225038-bf0da700-f7ac-11ea-8333-9bf79e10f40c.gif)

**Comment by Nikhil-Shenoy** [comment]
Late response, but yes, this solved the problem. Thank you!
