### ISSUE TITLE
m0 should  Multiply the first term, not all terms. 

### ISSUE THREAD

**Issue by Sunzhiliang** [neka-nat/probreg#40]
https://github.com/neka-nat/probreg/blob/769482171bde274de96e386f359e5bf4fa685c52/probreg/filterreg.py#L187

According to the paper and your formula,
m0 should  Multiply the first term, not all terms. 
 Like ( (m0  x np.squxare(t_source).sum(axis=1)   while not   (m0  x (np.square(t_source).sum(axis=1)

**Comment by neka-nat** [comment]
Hi @Sunzhiliang ,

Thank you for the suggestion.
The equation in the paper seems to be wrong.
The following issue is relevant.
https://github.com/neka-nat/probreg/issues/7

**Comment by Sunzhiliang** [comment]
I also check the c++ implementation in [gaowei](https://bitbucket.org/gaowei19951004/poser/src/master/corr_search/gmm/gmm_permutohedral_updatedvar_pt2pt.cpp)
In the source code, m1 and m2 have been  divided by m0, so m0/(m0+c) is all the terms.
However, the python implementation of yours doesn't do like it. Is my understanding wrong?
Thank you for your great work and replay.
![image](https://user-images.githubusercontent.com/34574779/94368495-e3577500-0116-11eb-9b53-189bde0fcd44.png)
![image](https://user-images.githubusercontent.com/34574779/94368546-20236c00-0117-11eb-8917-2c6a18311fc5.png)

**Comment by neka-nat** [comment]
Your suggestion is correct.
I attached the supplement that the author had previously published.
The post-transformation of equation (17) in this document is correct. (The multiplication of 3 is missing in the document...)

[filterreg_supplement.pdf](https://github.com/neka-nat/probreg/files/5288626/filterreg_supplement.pdf)

**Comment by neka-nat** [comment]
The fix has been pushed to master.
Thanks!
