### ISSUE TITLE
Does the outlier about “Bounding box”  not help much ?

### ISSUE THREAD

**Issue by Sunzhiliang** [neka-nat/probreg#41]
https://github.com/neka-nat/probreg/blob/769482171bde274de96e386f359e5bf4fa685c52/probreg/bcpd.py#L52

As the author said in the paper of BCPD, the  outlier about “Bounding box”   is set 1/V ,otherwise 0.  Does the outlier about “Bounding box”  not help much ?
 It is a bit difficult to verify this idea at the moment for me.

**Comment by neka-nat** [comment]
Thank you for the suggestion.
This is a simple implementation, so I'd like to try it out in the future.
