### ISSUE TITLE
The result of m0 m1,m2 return from  permutohedral.h

### ISSUE THREAD

**Issue by Sunzhiliang** [neka-nat/probreg#43]
https://github.com/neka-nat/probreg/blob/32077cf497f218ca45559503d8f0050376082434/probreg/filterreg.py#L160
 I'm a little confused about  the result of m0 m1,m2 return from  "permutohedral.h " in the source code.
Like，
 m0 = ph.filter(vin0, m).flatten()[:m]
 m1 = ph.filter(vin1, m)[:m]
Has the normalization factor of the normal distribution included in  m0  and m1?
If no , c should multiply   (2*sigma2*np.pi)**(D/2).
I try to find the result in the source code ,but failed. Can you help me ,thanks.

**Comment by neka-nat** [comment]
Thank you for finding the bug!
I've pushed the fix to master.
