### ISSUE TITLE
Test the algorithm in SLAM field

### ISSUE THREAD

**Issue by weisongwen** [neka-nat/probreg#44]
Hi @neka-nat , thanks for sharing such nice work! 

Have you tried any test of using your method with point clouds in the LiDAR SLAM field? e.g. compared your algorithm with ICP, NDT. LOAM in the robotics field.

Best,
Weisong,

**Comment by neka-nat** [comment]
Hi @weisongwen ,

Thank you for the question.
I have not tried these algorithms in SLAM.
I think that some algorithms are not suitable for SLAM.
GMMTree and Filterreg pt2pl seem to be better suited from a computational speed perspective.

**Comment by weisongwen** [comment]
Hi @neka-nat 

Thanks for your kind reply. Therefore, both the GMMTree and Filterreg pt2pl require Cuda support?

My understanding is that the probreg is more robust against the outlier points compared with the conventional ICP. Kindly please correct me if I am not correct.

Best,
Weisong,

**Comment by neka-nat** [comment]
Filterreg and GMMTree don't support CUDA, but Filterreg is a fast algorithm, even on the CPU.
And it is also more robust algorithm than ICP.
If you want to use the CUDA version of Filterreg, you can use the following library:
https://github.com/neka-nat/cupoch
However, it is only available in pt2pt.

**Comment by drlight-code** [comment]
The filterreg pt2pl objective (CPU implementation) used on my UAV mapping lidar data works amazingly well and really incredibly fast! This is very impressive. I prefilter the points in a planarity / normal estimation step and use only those points with a sufficiently reliable normal for the registration and apply the transform to the whole point set afterwards. I still have to do the exact timings, but I'm quite sure we should be able to treat our data in realtime with this. We have LiDAR scans of roughly 5000 points that arrive at 10Hz. @neka-nat great work! Is there any possibility that the pt2pl will be ported to cuda or a cpu-side c++ implementation?

**Comment by weisongwen** [comment]
Hi @neka-nat , Thanks for your kind reply. I believe that I should look into your paper first before I look into your code :-)

Best,
Weisong,

**Comment by weisongwen** [comment]
> Hi @neka-nat , Thanks for your kind reply. I believe that I should look into your paper first before I look into your code :-)
> 
> Best,
> Weisong,

Hi @drlight-code , have you compare the pt2pl with the ICP/LOAM/NDT like algorithms?

Best,
Weisong,

**Comment by drlight-code** [comment]
Hi @weisongwen, only with pt2pt ICP for now, which is an order of magnitude slower due to the nearest neighbor lookups.

**Comment by weisongwen** [comment]
Hi @drlight-code . Well noted with thanks :-)

**Comment by neka-nat** [comment]
Hi @drlight-code ,

A CUDA version of pt2pl will be implemented in (cupoch)[https://github.com/neka-nat/cupoch] in the future.
