### ISSUE TITLE
Should it be lmd * np.linalg.inv(gmat) as in the paper？

### ISSUE THREAD

**Issue by Sunzhiliang** [neka-nat/probreg#49]
https://github.com/neka-nat/probreg/blob/265658908b5857d497f3f37703acb6899a7bc63d/probreg/bcpd.py#L118
If we follow the paper,it shoud be
sigma_mat_inv = lmd * gmat + s2s2 * np.diag(nu).
However, if it is changed,the result is wrong. 
Is it  wrong to use "np.linalg.inv(gmat)" in the paper?

**Comment by neka-nat** [comment]
Thank you!
I've pushed fixes #48 and this issue to master.
Fixing both is working fine for the bunny.
