### ISSUE TITLE
Non-rigid cpd with bunny point clouds

### ISSUE THREAD

**Issue by sandwich25** [neka-nat/probreg#50]
Hi, I tried using the non-rigid CPD for the bunny point clouds in the example folder and used the following parameters:
lambda= 1.0e-9
maxiter= 100
tol= 0.000000000000001

But, there are 3 points not aligned as shown in the screenshot. How can I make those 3 points align properly?
<img width="552" alt="zoomed in" src="https://user-images.githubusercontent.com/69758962/95549931-d6f6e480-0a53-11eb-9b9d-ecfa2432d4fc.PNG">
<img width="1068" alt="zoomed out" src="https://user-images.githubusercontent.com/69758962/95549940-d9f1d500-0a53-11eb-9039-b9c3c396d67e.PNG">

**Comment by neka-nat** [comment]
I tried it in my environment and it seemed to be fine.
Is there any difference?

```py
import numpy as np
import open3d as o3
import transformations as trans
from probreg import cpd
from probreg import callbacks
import utils

source, target = utils.prepare_source_and_target_nonrigid_3d('bunny-x.txt',
                                                             'bunny-y.txt', 0.1)

cbs = [callbacks.Open3dVisualizerCallback(source, target)]
tf_param = cpd.registration_cpd(source, target, 'nonrigid',
                                lmd=1.0e-9, maxiter=100,
                                tol=0.000000000000001, callbacks=cbs)
```

![nonrigidcpd](https://user-images.githubusercontent.com/991515/95581882-b7bc7f00-0a74-11eb-8091-8bb0fd3cf2aa.png)

**Comment by sandwich25** [comment]
For me, I used bunny-y as source and bunny-x as target. Can you try that please?

**Comment by neka-nat** [comment]
Thank you!
I reproduced.
And I tuned the parameters again.
Try it out.

```py
import numpy as np
import open3d as o3
import transformations as trans
from probreg import cpd
from probreg import callbacks
import utils

source, target = utils.prepare_source_and_target_nonrigid_3d('bunny-y.txt',
                                                             'bunny-x.txt', 0.1)

cbs = [callbacks.Open3dVisualizerCallback(source, target)]
tf_param = cpd.registration_cpd(source, target, 'nonrigid',
                                lmd=1.0e-11, maxiter=100,
                                tol=0.000000000000001, callbacks=cbs)

```

![nonrigidcpd](https://user-images.githubusercontent.com/991515/95592345-7384ab00-0a83-11eb-8250-b3f46cd632a3.png)

**Comment by sandwich25** [comment]
There are still two points not aligned.

<img width="953" alt="Capture" src="https://user-images.githubusercontent.com/69758962/95594924-46da8e80-0a97-11eb-989a-ea9802b14753.PNG">

**Comment by neka-nat** [comment]
It's not easy to adjust.
What about the following?

```py
tf_param = cpd.registration_cpd(source, target, 'nonrigid',
                                lmd=1.0e-15, beta=20.0, maxiter=100,
                                tol=0.000000000000001, callbacks=cbs)

```

**Comment by sandwich25** [comment]
Two dots still not aligned. It's okay if you don't have the solution. Any idea on the reason this is happening?
<img width="951" alt="Capture2" src="https://user-images.githubusercontent.com/69758962/95602812-2f080800-0aa1-11eb-8838-c8434aa7cd3e.PNG">

**Comment by neka-nat** [comment]
It's a very divergent problem with CPD because the transformation is so large.
BCPD allows for a more stable convergence.

**Comment by sandwich25** [comment]
Thanks!
