### ISSUE TITLE
Question about the Permutohedral Lattice Filter used for FilterReg

### ISSUE THREAD

**Issue by GMNetto** [neka-nat/probreg#51]
Hi,

I noticed FilterReg has a step relying on an edge-aware filter for point-clouds in the expectation step in FilterReg. However, I could not find the source-code for it. I believe the c++ code has only a reference for it. I would like to know if this is the case. If it is, if you could point to it or make available this part.

Thank you,

**Comment by neka-nat** [comment]
Thank you for the question.
The permutohedral lattice filter can be found in the third_party folder.
https://github.com/neka-nat/probreg/tree/master/third_party/permutohedral

**Comment by GMNetto** [comment]
Do you think it would be possible to use this implementation to filter general point clouds? If it is, do you have some idea where to start to have this behavior?

**Comment by neka-nat** [comment]
I think it's possible if you refer to [the code](https://github.com/neka-nat/probreg/blob/master/probreg/filterreg.py#L79).
If your only goal is to filter point clouds, you can use PCL.
https://pointclouds.org/documentation/classpcl_1_1_permutohedral.html

**Comment by GMNetto** [comment]
Yes, I tried, but I am having problems to get any reasonable results from PCL's. I thought yours could give some help understanding the issue.

**Comment by neka-nat** [comment]
You can use the filter function as follows:

```py
import numpy as np
import open3d as o3
from probreg import gaussian_filtering
import utils

_, target = utils.prepare_source_and_target_rigid_3d('bunny.pcd')
tp = np.asarray(target.points)
sigma = 0.01
n = tp.shape[0]
ph = gaussian_filtering.Permutohedral(np.r_[tp, tp] / sigma)
out1 = ph.filter(np.r_[np.zeros((n, 1)), np.ones((n, 1))]).flatten()[:n]
out2 = ph.filter(np.r_[np.zeros_like(tp), tp])[:n]
out = o3.geometry.PointCloud()
out.points = o3.utility.Vector3dVector((out2.T / out1).T)

out.paint_uniform_color([0, 1, 0])
target.paint_uniform_color([0, 0, 1])
o3.visualization.draw_geometries([target, out])
```

![ph](https://user-images.githubusercontent.com/991515/95675922-a77fdd80-0bf5-11eb-9d67-dcbd3c4755a9.png)

**Comment by GMNetto** [comment]
Thanks for the example! Just one more question, this might be from my lack of understanding about the filter. Would you know why `tp` is always concatenated in the constructur of the Filter at `np.r_[tp, tp] ` and at `np.r_[np.zeros_like(tp), tp`? I was trying without them and getting no good results.

**Comment by neka-nat** [comment]
Equation 13 in [the original paper](https://arxiv.org/pdf/1811.10136.pdf) shows the reason.

**Comment by GMNetto** [comment]
Hi, I see, thanks for the quick answer. Just a final question about this normalization `(out2.T / out1).T`. If I understood correctly, this is not used by filterreg. Is this something particular for this use case (filter points)?

**Comment by neka-nat** [comment]
No, the same calculation is in filterreg.
https://github.com/neka-nat/probreg/blob/master/probreg/filterreg.py#L167

**Comment by GMNetto** [comment]
Ok, I was looking at the wrong function. Thank you very much! By the way, would you know the reason for such normalization?

**Comment by neka-nat** [comment]
Equation 14 in the original paper is helpful.
The permutohedral filter function calculates only the sum of the weights.

**Comment by GMNetto** [comment]
Ok, I saw it now. Thank you!
