### ISSUE TITLE
when I use the 'pt2pl' sometimes,Why all the elements in “m0”   could be zero, 

### ISSUE THREAD

**Issue by Sunzhiliang** [neka-nat/probreg#52]
https://github.com/neka-nat/probreg/blob/169c8d7e234203ff76f620682ed945c06416ff58/probreg/filterreg.py#L164
I am in  trouble  about  the  'pt2pl' in "filterreg" ,
when I use some data set,
why all the elements in “m0”   could be zero,  while some other data is OK? 
I think the "sigma2"  has a influence about it. 
Have you encountered this kind of problem？

**Comment by neka-nat** [comment]
Hi,
Thank you for asking.
If the data are too far apart from each other, I think m0 becomes zero.
What kind of data is that?

**Comment by Sunzhiliang** [comment]
I use the  date set of 
 "redwood\livingroom ,"cloud_bin_0"    and   "cloud_bin_4"   ".
"bunuy000 and  bunuy090"
I try to change  the  initial "sigma2" or the "maxiter" , the problem can be solved.

**Comment by neka-nat** [comment]
Thanks.
Can I get a link to the data?
Bunny has much curved surface, so pt2pl may not be suitable for it.

**Comment by Sunzhiliang** [comment]
Here is it.
[http://redwood-data.org/indoor/registration.html](url)
![image](https://user-images.githubusercontent.com/34574779/95881388-1ce0df00-0dab-11eb-9ab6-6598899a04c6.png)
