### ISSUE TITLE
Question on Variables

### ISSUE THREAD

**Issue by sandwich25** [neka-nat/probreg#53]
Hi,

I have read your documentation and I have a quick question on what these variables actually represents: n_p, p1, pt1, px, q, sigma2, and transformation.
<img width="329" alt="Capture5" src="https://user-images.githubusercontent.com/69758962/96158079-d7fda980-0f5e-11eb-90be-1264ac37bb9e.PNG">

**Comment by neka-nat** [comment]
For estep variables, I am referring to the variable names in the paper.
https://arxiv.org/pdf/0905.2635.pdf
`p` is the posterior probability matrix.
`p1` is the sum of the direction of p.
`pt1` is the columnar sum of p.
`px` is the multiplication of p and the target point cloud.
`n_p` is the total sum of p.

For mstep,
`q` is a result of log-likelihood function.
`sigma2` is a variance.
`transformation` indicates a transformation(rotation matrix, translate vector, scaling or nonrigid term).

**Comment by sandwich25** [comment]
Thank you so much, another question, comparing non-rigid and rigid CPD, does non-rigid CPD always disregard outliers? I already input various w value which does not improve the non rigid alignment compared to rigid. In what situation is it best to use rigid alignment and non-rigid alignment respectively?
Rigid result:
<img width="848" alt="Rigid result" src="https://user-images.githubusercontent.com/69758962/96471072-aa747100-127a-11eb-8ffa-05bdc262ebcf.png">
Non-rigid result:
<img width="507" alt="NonRigid_zoomed_in" src="https://user-images.githubusercontent.com/69758962/96471132-b8c28d00-127a-11eb-8651-fb73b5733a60.png">

**Comment by neka-nat** [comment]
The use of rigid and nonrigid registration should depend on the object matter.
I believe that nonrigid registration should be applied to objects that can change shape, such as humans and other living things.
You should use the rigid registration for rigid objects like the one above.

**Comment by sandwich25** [comment]
I see, that makes sense. Thank you for the clarification!

**Comment by sandwich25** [comment]
Sorry, I have another question, how do we know how many Gaussians are there in the GMM?

**Comment by neka-nat** [comment]
For CPD, the number of points in the target point cloud is the number of components for the GMM.

**Comment by sandwich25** [comment]
Thanks!

**Comment by sandwich25** [comment]
Sorry, just for confirmation, so even though the source point cloud is treated as GMM centroids, the points in the target point clouds is the number of components for GMM?

**Comment by sandwich25** [comment]
Alright, thanks again!
