### ISSUE TITLE
Does not recognize prepare_source_and_target_rigid_3d from util

### ISSUE THREAD

**Issue by Angit16** [neka-nat/probreg#54]
Hi,

I was executing "gmmtree_rigid.py". I found the following error.

```
 source, target = utils.prepare_source_and_target_rigid_3d('/home/anindya/bunny.pcd', n_random=0)
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
 AttributeError: module 'utils' has no attribute 'prepare_source_and_target_rigid_3d'
```
could you suggest any solution?

regards,
Ani

**Comment by neka-nat** [comment]
Thanks you for the question.
It's possible that you are loading the different `utils` module.
prepare_source_and_target_rigid_3d is in utils.py in example.
https://github.com/neka-nat/probreg/blob/master/examples/utils.py

**Comment by Angit16** [comment]
Yes, I have seen that, and I am sure python3 in my system is using some other utils.py, as there are many of them. But how do I resolve it?

thank you,

**Comment by neka-nat** [comment]
It depends on your environment, so I'm not sure what solution you need.
It is possible to control the import order in several ways, so I think you should look into it.

https://stackoverflow.com/questions/9586630/python-paths-and-import-order
https://stackoverflow.com/questions/33737426/python-import-order

**Comment by Angit16** [comment]
thank you, let me check it.
