### ISSUE TITLE
Understanding the transformation.DeformableKinematicModel.SkinningWeight semantics

### ISSUE THREAD

**Issue by GMNetto** [neka-nat/probreg#55]
Hi,

I am taking a look at the filterreg deformable example and I am having trouble understanding the skinning weights pair representation. In the paper, the weight if I understook correctly, is a number expressing the proximity between a reference point and one of its nearest neighbors. In the example, I noticed the usage of "pairs" and "vals", each being a length 2 list and existing for each input point. My question is how this representation express the weight relationship among the ponts? Or, if I understood wrongly from the start, what would be the semantics for this skinning weight representation?

Thank you

**Comment by neka-nat** [comment]
Hi,
Thank you for the question.
The weights don't represent proximity to the reference point.
The weights are used to the weighted average of multiple rigid body transformations.
For more information on dual quaternion skinning, you can refer to the following references:
https://www.cs.utah.edu/~ladislav/kavan07skinning/kavan07skinning.pdf

**Comment by GMNetto** [comment]
Hi, thanks for the reply. Yes, I noticed that and the paper indeed help me understand better. However, I am still having issues understanding the weights representation in the example 
```python
for i in range(n_points):
    ws['pair'][i][0] = 0
    ws['pair'][i][1] = 1
for i in range(n_points):
    ws['val'][i][0] = float(i) / n_points
    ws['val'][i][1] = 1.0 - float(i) / n_points
```
. Each `ws['pair'][i]` and `ws['val'][i]` represent a joint? If so, what would `ws['pair'][i][0]` represent?

Thank you

**Comment by neka-nat** [comment]
The documentation explains.
https://github.com/neka-nat/probreg/blob/master/probreg/transformation.py#L164
