### ISSUE TITLE
Full author list

### ISSUE THREAD

**Issue by eiiijiiiy** [neka-nat/probreg#56]
Hello, dear author!

May I know the full list of the authors for a strict citation format?

Thank you so much.

**Comment by neka-nat** [comment]
Thank you for the question.
A list of all contributors.
@neka-nat (Kenta Tanaka)
@drlight-code
@cmatija
@pramukta
But, unfortunately, I don't know their real names...

**Comment by drlight-code** [comment]
@drlight-code Patric Schmitz

**Comment by cmatija** [comment]
@cmatija Matija Ciganovic

**Comment by eiiijiiiy** [comment]
Thank you so much for all your nice reply :)

**Comment by eiiijiiiy** [comment]
Thanks a lot ：）
