### ISSUE TITLE
How to evalute the registration results?

### ISSUE THREAD

**Issue by Yellowshuohahaha** [neka-nat/probreg#58]
Is there any API?

**Comment by neka-nat** [comment]
Hi @Yellowshuohahaha ,

Thank you for the question.
I think #42 will be helpful.

**Comment by Yellowshuohahaha** [comment]
Thanks a lot! That will be useful.

**Comment by SabraHashemi** [comment]
@Yellowshuohahaha  how did you add kdtree to code?
