### ISSUE TITLE
the rigid registration of BCPD can't  be implemented by changing the k to 1.0e20.

### ISSUE THREAD

**Issue by Sunzhiliang** [neka-nat/probreg#59]
Hi, I'm back again.   Is The rigid registration of BCPD  not easy to integrated in the  nonRigid framework? As the paper said, the rigid registration can be  implemented by  just changing the k to 1.0e20( a large number).

**Comment by neka-nat** [comment]
Hi,

Thank you for the suggestion.
I tried a little bit with the following parameters. (In the paper lamda is also set to a large value.)

```py
import numpy as np
import open3d as o3
import transformations as trans
from probreg import bcpd
from probreg import callbacks
import utils

source, target = utils.prepare_source_and_target_rigid_3d('bunny.pcd')

cbs = [callbacks.Open3dVisualizerCallback(source, target)]
tf_param = bcpd.registration_bcpd(source, target,
                                  callbacks=cbs, maxiter=100, tol=1.0e-9,
                                  w=0.1, lmd=1.0e10, k=1.0e80, gamma=0.5)
rot = trans.identity_matrix()
rot[:3, :3] = tf_param.rigid_trans.rot
print("result: ", np.rad2deg(trans.euler_from_matrix(rot)),
      tf_param.rigid_trans.scale, tf_param.rigid_trans.t)
```

It behaves like a rigid, but it doesn't converge.
I think I need to tune the parameters or debug the code.

![bcpd_rigid](https://user-images.githubusercontent.com/991515/100516612-70c34e00-31c8-11eb-9ec9-e5903e050c0e.png)
