### ISSUE TITLE
Question about rigid CPD Maximization Step

### ISSUE THREAD

**Issue by mli0603** [neka-nat/probreg#60]
Hello Shirokuma,

Thank you so much for your work. I have a question about the maximization step for rigid CPD, specifically, the **A matrix** computed [here](https://github.com/neka-nat/probreg/blob/master/probreg/cpd.py#L138)

```python
a = xp.dot(px.T, source_hat) - xp.outer(mu_x, xp.dot(p1.T, source_hat))
```

It seems to be different from the [paper](https://arxiv.org/pdf/0905.2635.pdf). In the paper, the A matrix is the product from both target points X and source points Y,
![image](https://user-images.githubusercontent.com/13513172/100903278-b36c7b00-3493-11eb-9617-346e4d5d1afa.png)
But in the code it only uses source points and they look different. 

Can you explain why these two equations are identical? Thank you again!

**Comment by neka-nat** [comment]
Hi,

Thank you for the question.
The `px` represents the multiplication of P and X.
We can also derive the above equation by substituting X-ux into X^.

**Comment by mli0603** [comment]
Oh I think I see how it works. Am I correct about the following?
```python
a = xp.dot(px.T, source_hat) - xp.outer(mu_x, xp.dot(p1.T, source_hat))
a = xp.dot(px.T, source_hat) - xp.dot(xp.outer(mu_x, p1.T), source_hat))
a = xp.dot(px.T - xp.outer(mu_x, p1.T), source_hat)
a = xp.dot(xp.dot(x.T-mu_x, p.T), source_hat)
```
The last line is the equation from the paper.

**Comment by neka-nat** [comment]
Nice transformation!
