### ISSUE TITLE
Microsoft visual build error !

### ISSUE THREAD

**Issue by SyedAli-SAM** [neka-nat/probreg#66]
Hi, 
I have installed cupy-cuda90 using pip install cupy-cuda90 after that i installed probreg using pip install probreg but it gave me following error: 
Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools"

I have checked Microsoft build version on my laptop which is 14.2 (through program/features control panel option), why i am getting this error if i already have 14.2 ? 
Please help me with this

**Comment by neka-nat** [comment]
Thanks for the question!
I don't think the path is working.
Please configure the terminal where you run pip so that `cl.exe` can be run.

**Comment by SyedAli-SAM** [comment]
Thanks for the reply! I just reinstalled it using Microsoft visual installer and issue is fixed but now its giving me following error;

c:\python39\include\pyconfig.h(200): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory

I have search for this problem and found that it can be fixed by installing anaconda. I am going to install anaconda but if by any chance it didn't work can you suggest me something else?

Thanks in advance !

**Comment by neka-nat** [comment]
The following may be helpful.
https://stackoverflow.com/questions/23691564/running-cython-in-windows-x64-fatal-error-c1083-cannot-open-include-file-ba/42624713#42624713
https://social.msdn.microsoft.com/Forums/en-US/7843071f-0767-4af4-b645-508e3ffcf56f/visual-c-fatal-error-c1083-cannot-open-include-file?forum=Vsexpressvc
https://stackoverflow.com/questions/44437357/fatal-error-c1083-cannot-open-include-file-basetsd-h

**Comment by SyedAli-SAM** [comment]
after fixing basetsd,h error through the link you provided (https://stackoverflow.com/questions/23691564/running-cython-in-windows-x64-fatal-error-c1083-cannot-open-include-file-ba/42624713#42624713) . I got another issue regarding rc.exe which i fixed through this link _https://www.tutorialexample.com/fix-python-pip-install-link-fatal-error-lnk1158-cannot-run-rc-exe-error-python-tutorial/_
 
Now i am getting following error in which i cannot point out the main error. Please Help !

**Installing collected packages: transformations, scikit-learn, open3d-python, matplotlib, probreg
    Running setup.py install for transformations ... done
    Running setup.py install for probreg ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\admin\pycharmprojects\project\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppDat
a\\Local\\Temp\\pip-install-iapmlcg4\\probreg_ff3e1a774b224d70876f848c220346e1\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-iapml
cg4\\probreg_ff3e1a774b224d70876f848c220346e1\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f
.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Admin\AppData\Local\Temp\pip-record-0zzky9lf\install-record.txt' --single-version-e
xternally-managed --compile --install-headers 'c:\users\admin\pycharmprojects\fypproject\venv\include\site\python3.9\probreg'
         cwd: C:\Users\Admin\AppData\Local\Temp\pip-install-iapmlcg4\probreg_ff3e1a774b224d70876f848c220346e1\
    Complete output (88 lines):
    Found Eigen version 3.3.90 in: third_party/eigen
    Found Eigen version 3.3.90 in: third_party/eigen
    Found Eigen version 3.3.90 in: third_party/eigen
    Found Eigen version 3.3.90 in: third_party/eigen
    Found Eigen version 3.3.90 in: third_party/eigen
    Found Eigen version 3.3.90 in: third_party/eigen
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\probreg
    copying probreg\callbacks.py -> build\lib.win-amd64-3.9\probreg
    copying probreg\cost_functions.py -> build\lib.win-amd64-3.9\probreg
    copying probreg\cpd.py -> build\lib.win-amd64-3.9\probreg
    copying probreg\features.py -> build\lib.win-amd64-3.9\probreg
    copying probreg\filterreg.py -> build\lib.win-amd64-3.9\probreg
    copying probreg\gaussian_filtering.py -> build\lib.win-amd64-3.9\probreg
    copying probreg\gauss_transform.py -> build\lib.win-amd64-3.9\probreg
    copying probreg\gmmtree.py -> build\lib.win-amd64-3.9\probreg
    copying probreg\l2dist_regs.py -> build\lib.win-amd64-3.9\probreg
    copying probreg\math_utils.py -> build\lib.win-amd64-3.9\probreg
    copying probreg\se3_op.py -> build\lib.win-amd64-3.9\probreg
    copying probreg\transformation.py -> build\lib.win-amd64-3.9\probreg
    copying probreg\xxpy.py -> build\lib.win-amd64-3.9\probreg
    copying probreg\__init__.py -> build\lib.win-amd64-3.9\probreg
    running build_ext
    building 'probreg._ifgt' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\probreg
    creating build\temp.win-amd64-3.9\Release\probreg\cc
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\admin\pycharmprojects\fypproject\venv\l
ib\site-packages\pybind11\include -Ic:\users\admin\pycharmprojects\fypproject\venv\lib\site-packages\pybind11\include -Ithird_party/eigen -Ic:\users\admin\pycharmproj
ects\fypproject\venv\include -IC:\Python39\include -IC:\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE -IC:\Program Files (x86)\Mic
rosoft Visual Studio 14.0\VC\ATLMFC\INCLUDE -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.1
9041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt /EHsc /Tpprobreg/cc
/ifgt.cc /Fobuild\temp.win-amd64-3.9\Release\probreg/cc/ifgt.obj /EHsc /DVERSION_INFO=\"0.1.7\"
    ifgt.cc
    probreg/cc/ifgt.cc(37): warning C4244: '*=': conversion from 'double' to 'probreg::Float', possible loss of data
    probreg/cc/ifgt.cc(45): warning C4244: 'initializing': conversion from 'const double' to 'probreg::Float', possible loss of data
    probreg/cc/ifgt.cc(45): warning C4244: 'initializing': conversion from 'const double' to 'const probreg::Float', possible loss of data
    probreg/cc/ifgt.cc(51): warning C4244: 'initializing': conversion from 'double' to 'probreg::Float', possible loss of data
    probreg/cc/ifgt.cc(51): warning C4244: 'initializing': conversion from 'double' to 'const probreg::Float', possible loss of data
    probreg/cc/ifgt.cc(102): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'probreg::Integer', possible loss of data
            with
            [
                Derived=Eigen::Matrix<float,-1,-1,0,-1,-1>
            ]
    probreg/cc/ifgt.cc(102): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'const probreg::Integer', possible loss of data
            with
            [
                Derived=Eigen::Matrix<float,-1,-1,0,-1,-1>
            ]
    probreg/cc/ifgt.cc(104): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'probreg::Integer', possible loss of data
            with
            [
                Derived=Eigen::Matrix<float,-1,-1,0,-1,-1>
            ]
    probreg/cc/ifgt.cc(109): warning C4244: 'initializing': conversion from 'const double' to 'probreg::Float', possible loss of data
    probreg/cc/ifgt.cc(109): warning C4244: 'initializing': conversion from 'const double' to 'const probreg::Float', possible loss of data
    probreg/cc/ifgt.cc(110): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'probreg::Integer', possible loss of data
            with
            [
                Derived=Eigen::Matrix<float,-1,-1,0,-1,-1>
            ]
    probreg/cc/ifgt.cc(111): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'probreg::Integer', possible loss of data
            with
            [
                Derived=Eigen::Matrix<float,-1,-1,0,-1,-1>
            ]
    probreg/cc/ifgt.cc(112): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'probreg::Integer', possible loss of data
            with
            [
                Derived=Eigen::Matrix<float,-1,-1,0,-1,-1>
            ]
    probreg/cc/ifgt.cc(128): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'probreg::Integer', possible loss of data
            with
            [
                Derived=Eigen::Matrix<float,-1,-1,0,-1,-1>
            ]
    probreg/cc/ifgt.cc(142): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'probreg::Integer', possible loss of data
            with
            [
                Derived=Eigen::Matrix<float,-1,-1,0,-1,-1>
            ]
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\admin\pycharmprojects\fypproject\venv\l
ib\site-packages\pybind11\include -Ic:\users\admin\pycharmprojects\fypproject\venv\lib\site-packages\pybind11\include -Ithird_party/eigen -Ic:\users\admin\pycharmproj
ects\fypproject\venv\include -IC:\Python39\include -IC:\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE -IC:\Program Files (x86)\Mic
rosoft Visual Studio 14.0\VC\ATLMFC\INCLUDE -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.1
9041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt /EHsc /Tpprobreg/cc
/ifgt_py.cc /Fobuild\temp.win-amd64-3.9\Release\probreg/cc/ifgt_py.obj /EHsc /DVERSION_INFO=\"0.1.7\"
    ifgt_py.cc
    probreg/cc/ifgt_py.cc(14): warning C4305: 'argument': truncation from 'double' to 'probreg::Float'
    probreg/cc/ifgt_py.cc(19): error C2017: illegal escape sequence
    probreg/cc/ifgt_py.cc(19): error C2001: newline in constant
    probreg/cc/ifgt_py.cc(23): error C2143: syntax error: missing ';' before '}'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\admin\pycharmprojects\fypproject\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0
] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-iapmlcg4\\probreg_ff3e1a774b224d70876f848c220346e1\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppDat
a\\Local\\Temp\\pip-install-iapmlcg4\\probreg_ff3e1a774b224d70876f848c220346e1\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replac
e('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Admin\AppData\Local\Temp\pip-record-0zzky9lf\insta
ll-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\admin\pycharmprojects\fypproject\venv\include\site\python3.9\probreg' Check t
he logs for full command output.**

**Comment by neka-nat** [comment]
On CI, I can build with VS2017.
https://ci.appveyor.com/project/neka-nat/probreg/builds/38552028
Please try to build with VS2017.

**Comment by SyedAli-SAM** [comment]
Thanks for the help but uninstalled and started again from "python 3.6 installation" and followed the same steps but this time i created a file in your example folder and ran it through python idle which worked for me!
