### ISSUE TITLE
Any method to describe the similarity of two point clouds? 

### ISSUE THREAD

**Issue by Faultiness** [neka-nat/probreg#67]
Thanks for developing such a useful tool in Python.

Is there any build-in method to describe the similarity of two points cloud AFTER transformation? I tried to use average point-to-point Euclidean distance but this method will fail when the number of point pairs is different. I noticed that there is a tol parameter when processing, but it seems that I cannot find a built-in method that can be actively called and calculate tol after transformation. Any suggestion?

**Comment by Faultiness** [comment]
#42 perfectly solved my problem. Thanks again for such a useful tool~

**Comment by SabraHashemi** [comment]
@Faultiness  how did you add his to code?
