### ISSUE TITLE
Custom objective or how to restrict set of posible rigid transformations to a single axis of rotation

### ISSUE THREAD

**Issue by mariabauza** [neka-nat/probreg#68]
Thanks for probreg, I have been using it for the last 2 years!
I would like to know if it is possible to add constraints or additional parameters in any of the optimization functions. Is that functionality available in probreg?

In case it is easier, my problem consists of 3D point clouds, and all I need is that registration transforms are restricted to rotations about the z-axis (like in the 2d case, but my pointclouds are 3D).

Thanks a lot!

**Comment by neka-nat** [comment]
Thanks!
Sorry for the late reply.
I think it is possible once you decide on the algorithm and constraints.
For example, "CPD with fixed Z-axis calculation".
On the other hand, it is difficult to make an interface where you can freely give constraints.
What is the algorithm and constraint you want to deal with?
