### ISSUE TITLE
update parameter sigma

### ISSUE THREAD

**Issue by cbenitez81** [neka-nat/probreg#7]
Thanks for the code, it's great
I think that there is small bug in the code for [filterreg](https://github.com/neka-nat/probreg/blob/deformable_kinematic/probreg/filterreg.py) in the following line
```
sigma2 = ((m0 * np.square(t_source).sum(axis=1) - 2.0 * (t_source * m1).sum(axis=1) + m2) / (m0 + c)).sum()
```
In equation (17) of the supplementary material there is a small mistake from the first line to the second one, m0 should multiply the whole numerator, I believe that it should be

```
sigma2 = (m0 *( np.square(t_source).sum(axis=1) - 2.0 * (t_source * m1).sum(axis=1) + m2) / (m0 + c)).sum()
```
And then
```
sigma2 /= (3*m0m0.sum())
```
I check the c++ implementation and it's as I'm suggesting

Let me know!!

**Comment by neka-nat** [comment]
Hi @cbenitez81,

Thank you for good suggestion!
I checked the paper and [the original code](https://bitbucket.org/gaowei19951004/poser/src/master/corr_search/gmm/gmm_permutohedral_updatedvar_pt2pt.cpp#lines-148).
You must be right.

Will you send a pull request if possible?

**Comment by cbenitez81** [comment]
Let me make another couple of changes if I have time next week. I think that we can improve the speed if we run the filter once for the reference cloud and prevent the hash table of growing for the model cloud.

**Comment by neka-nat** [comment]
Sounds great.
I'm looking forward to the improvement.

**Comment by neka-nat** [comment]
I corrected the calculation of simga2.
https://github.com/neka-nat/probreg/commit/06013f2c5d4a8f9a1574d5f4bd684e9438986d4e
Thanks to this, calculation accuracy has improved.
Please let me know if there are any improvements.

**Comment by cbenitez81** [comment]
Sure thing, I haven't had time but I started another filter approach, as
soon is tested, I'll let you know
