### ISSUE TITLE
Feature Request: Support for Open3D's '.xyz' Point Cloud Format 

### ISSUE THREAD

**Issue by uneron** [neka-nat/probreg#71]
I'm trying to apply the `probreg` algorithms on point clouds that are decoded in the simple `.xyz` format of Open3D.
If I import anything from `probreg` to my python script, the loaded point cloud becomes somehow invalid.
This even happen while no function from probreg is executed.

Here is some example code:
```python
import open3d as o3d

source = o3d.io.read_point_cloud("point-cloud.xyz")
print(source)

o3d.visualization.draw_geometries([source])
```
```
# output

PointCloud with 32972 points.
```
And a properly visualized point cloud.

---
On the other hand:
```python
from probreg import cpd
import open3d as o3d

source = o3d.io.read_point_cloud("point-cloud.xyz")
print(source)

o3d.visualization.draw_geometries([source])
```
```
# output

PointCloud with 0 points.
```
and a blank Open3D window.

**Comment by neka-nat** [comment]
Hi,
Thank you for the reporting.
Can you send me the pointcloud data where the bug occurred?

**Comment by uneron** [comment]
Unfortunately not.
You could try it by yourself by converting the example bunny pcd to an xyz.
The workaround mentioned in #72 already helped.
 We added it to the data read in pipeline.
