### ISSUE TITLE
Bug Report: Probreg does not work for ASCII .pcd

### ISSUE THREAD

**Issue by uneron** [neka-nat/probreg#72]
In a similar manner as in #71, `probreg` does not support `.pcd` files that are encoded in ASCII. Only the binary format works fine.
This is not directly noticeable because the data is acquired, but incorrectly, displayed at a significantly lower sample rate and, above all, also processed through the algorithms at this lower resolution.

---
For now there is a work around by utilizing [`convert_pcd_ascii_binary` from PCL](https://github.com/PointCloudLibrary/pcl/blob/master/io/tools/convert_pcd_ascii_binary.cpp).

```
Syntax is: ./pcl_convert_pcd_ascii_binary <file_in.pcd> <file_out.pcd> 0/1/2 (ascii/binary/binary_compressed)
```
In this case, the point cloud is represented correctly when option `1` is used.

**Comment by neka-nat** [comment]
Thanks for the report!
Sorry, I couldn't reproduce this bug on my environment.
Can you send me the pointcloud data?
I used [this data](https://drive.google.com/file/d/1en2SltWjkb3sZ9mXQr-QwJNeGCS1rRnf/view?usp=sharing).

```py
import open3d as o3d
# import probreg

pcd = o3d.io.read_point_cloud("bunny_ascii.pcd")
print(pcd)
o3d.visualization.draw_geometries([pcd])
```

**Comment by uneron** [comment]
As mentioned in #71, unfortunately I'm not allowed to share the data.
But I think the header should be fine, even with some coordinates:

```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z
SIZE 4 4 4
TYPE F F F
WIDTH 32975
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 32975
DATA ascii
11.7143 8.41913 0.0036869
11.8276 8.37446 0.00370026
11.8169 8.2472 0.00306225
[...]
```

**Comment by neka-nat** [comment]
Thanks!
I can't debug with just the header, but it looks fine from the header...
Did this bug happen with any other data?
