### ISSUE TITLE
no `update_scale` for GMMTree and FilterReg

### ISSUE THREAD

**Issue by humanpose1** [neka-nat/probreg#74]
Hi,
Thanks a lot for your amazing library.
There is a parameter `update_scale` for [CPD](https://github.com/neka-nat/probreg/blob/ff0e5e08d0d0185e040cc01c3a853bf76568fa75/probreg/cpd.py#L108) but not for [GMMTree](https://github.com/neka-nat/probreg/blob/master/probreg/gmmtree.py) or [FilterReg](https://github.com/neka-nat/probreg/blob/ff0e5e08d0d0185e040cc01c3a853bf76568fa75/probreg/filterreg.py#L47).

**Comment by neka-nat** [comment]
The original papers on filterreg and gmmtree do not support scale.
I think it is possible to formulate and implement it.
