### ISSUE TITLE
Issue in cpd_nonrigid3d_cuda.py for newly generated PCDs(source and target) of SMPLX models

### ISSUE THREAD

**Issue by SyedAli-SAM** [neka-nat/probreg#75]
hello there i hope you are doing well. I want to apply non rigid iterative closest point algorithm using two point clouds in which one is source and the other is target ( .xyz format). I already ran cpd_nonrigid3d_cuda.py script using face-x.txt and face-y.txt which gives me following output;

![image](https://user-images.githubusercontent.com/45313513/132971409-9356b391-55a9-4b8f-8e09-1709f6d969f8.png)

Now when i used SMPLX pcds (source and target) it gives me following;

![image](https://user-images.githubusercontent.com/45313513/132971501-8570e0b7-b180-4523-84c3-e4d025805bfb.png)

![image](https://user-images.githubusercontent.com/45313513/132971511-28e3bd91-67b2-4eff-9067-011056ceb632.png)

**SMPLX SOURCE PCD:**

![image](https://user-images.githubusercontent.com/45313513/132971572-ed86c4de-d7ac-4162-9c9c-cf006e0d80f1.png)

**SMPLX TARGET PCD:**

![image](https://user-images.githubusercontent.com/45313513/132971646-61a2192d-0b4d-44dd-9bcf-7228e2260781.png)

I am a beginner in this so please can you help me with this ? Thanks.

**Comment by neka-nat** [comment]
The point cloud in SMPLX seems to be loading only one point.
Is this a problem with Open3D?
![132971511-28e3bd91-67b2-4eff-9067-011056ceb632](https://user-images.githubusercontent.com/991515/133169172-fde75bd0-2195-4460-b154-9abb98c81da1.png)

**Comment by SyedAli-SAM** [comment]
I guess not because open3d is reading a single PCD file and visualizing it in open 3d which gives the following output;

![image](https://user-images.githubusercontent.com/45313513/133479658-bb39c407-4f06-4bf4-afb6-5e95345eb35f.png)

**Comment by neka-nat** [comment]
Can you share the point cloud?
I will try to calculate it in my environment.

**Comment by SyedAli-SAM** [comment]
[pointCloudWithMorePointstxt.txt](https://github.com/neka-nat/probreg/files/7184595/pointCloudWithMorePointstxt.txt)

**Comment by SyedAli-SAM** [comment]
[modifiedPCDMale(SourceOrTarget).txt](https://github.com/neka-nat/probreg/files/7184633/modifiedPCDMale.SourceOrTarget.txt)
[PCDMale(SourceOrTarget).txt](https://github.com/neka-nat/probreg/files/7184635/PCDMale.SourceOrTarget.txt)

**Comment by SyedAli-SAM** [comment]
Hello there i hope you are fine. If i am able to help you with anything please let me know. Thanks!

**Comment by neka-nat** [comment]
I am sorry for the delay in replying.
Please try to run it with the following code.

```py
import numpy as np
use_cuda = True
if use_cuda:
    import cupy as cp
    to_cpu = cp.asnumpy
    cp.cuda.set_allocator(cp.cuda.MemoryPool().malloc)
else:
    cp = np
    to_cpu = lambda x: x
import open3d as o3
from probreg import cpd
from probreg import callbacks
import utils
import time

source, target = utils.prepare_source_and_target_nonrigid_3d(
    'PCDMale.SourceOrTarget.txt',
    'modifiedPCDMale.SourceOrTarget.txt',
    voxel_size=0.01
)
source_pt = cp.asarray(source.points, dtype=cp.float32)
target_pt = cp.asarray(target.points, dtype=cp.float32)

acpd = cpd.NonRigidCPD(source_pt, use_cuda=use_cuda)
start = time.time()
tf_param, _, _ = acpd.registration(target_pt, maxiter=100, tol=1.0e-6)
elapsed = time.time() - start
print("time: ", elapsed)

print("result: ", to_cpu(tf_param.w), to_cpu(tf_param.g))

result = tf_param.transform(source_pt)
pc = o3.geometry.PointCloud()
pc.points = o3.utility.Vector3dVector(to_cpu(result))
pc.paint_uniform_color([0, 1, 0])
target.paint_uniform_color([0, 0, 1])
o3.visualization.draw_geometries([pc, target])
```

You will get the following result
![result_issue75](https://user-images.githubusercontent.com/991515/141994100-0b1670f8-bbd8-41fd-aae9-fd35c0aeb6b4.png)
.
