### ISSUE TITLE
How to interpret nonrigid CPD transform results?

### ISSUE THREAD

**Issue by TigerHix** [neka-nat/probreg#77]
First of all, thank you for this incredible library and the vast amount of examples you provided!

I would like to know how to interpret the return results of `NonRigidTransformation.transform()`. For a `RigidTransformation`, calling the `transform()` with one point (say `tf_param.transform([1, 1, 1])`) returns one transformed point. However, for a `NonRigidTransformation`, calling the `transform()` with one point actually returns N points, where N is the number of registered points.

My questions are:
1) What do the N points returned represent?
2) How do I transform only one point?

Thanks!

**Comment by neka-nat** [comment]
Hi,
Thank you for the question!
Since `NonRigidTransformation` uses the model point cloud to calculate the kernel in advance, you need to initialize it again if you change the model point cloud.

```py
model_pt = np.array([[1, 1, 1]])
nrt = NonRigidTransformation(w, model)
transformed_pt = nrt.transform(model)
```

At this time you will get only one point.
