### ISSUE TITLE
Help on registering bottom and upper point cloud parts

### ISSUE THREAD

**Issue by ttsesm** [neka-nat/probreg#79]
Hi @neka-nat,

I have two parts of a complete point cloud, i.e. the upper and bottom parts (see attached files) which I would like to align. Considering that the original ICP from open3d did not work as good as I was expecting and looking around I found your lib which looked promising, thus I gave it a try. However, as you can see the results are not the best as well:

CPD:
![cpd](https://user-images.githubusercontent.com/10189018/143897143-0ead6edd-f89e-4be7-a521-2b0c7d84c2c3.png)

SVR:
![svr](https://user-images.githubusercontent.com/10189018/143897166-ef1e1d2b-d2de-41dc-92f6-e1bed537d38f.png)

Filter_reg:
![filterreg](https://user-images.githubusercontent.com/10189018/143897232-4ca44c08-b24b-46e4-9af5-07b973af9ac8.png)

Thus, I wanted to ask whether you have any idea how I could improve the output.

The code snippet I used is the following:

```
import os
import sys
import copy
import numpy as np
import open3d as o3d
import probreg as pr
import transforms3d as t3d

mesh1 = o3d.io.read_triangle_mesh("../data/Tombstone1_p1.obj", enable_post_processing=True, print_progress=True)
mesh2 = o3d.io.read_triangle_mesh("../data/Tombstone1_p2.obj", enable_post_processing=True, print_progress=True)

pcd1 = o3d.geometry.PointCloud(mesh1.vertices)
pcd1.normals = mesh1.vertex_normals

pcd2 = o3d.geometry.PointCloud(mesh2.vertices)
pcd2.normals = mesh2.vertex_normals

# tf_param, _, _ = pr.cpd.registration_cpd(pcd1, pcd2)
# tf_param = pr.l2dist_regs.registration_svr(pcd1,pcd2)
tf_param, _, _ = pr.filterreg.registration_filterreg(pcd1, pcd2)

result = copy.deepcopy(pcd1)
result.points = tf_param.transform(result.points)

print("Matrix: \n{}\n".format(np.column_stack([tf_param.rot, tf_param.t])))

# draw result
pcd1.paint_uniform_color([1, 0, 0])
pcd2.paint_uniform_color([0, 1, 0])
result.paint_uniform_color([0, 0, 1])
o3d.visualization.draw_geometries([pcd1, pcd2, result])
```

Thanks.

[data.zip](https://github.com/neka-nat/probreg/files/7619264/data.zip)

**Comment by drlight-code** [comment]
It's not easy to even match the two by looking at the data. What would be the result that you expect, I guess the CPD image with the blue model rotated 180 degree around the "up"axis? Do the two models even share an overlap region?
It is a difficult setting because any registration algorithm will try to bring *all* points close to each other. since they have a roughly identical outline that will always give a result where the two models align, and intersect, as in the CPD and FilterReg case. 
One thing you could try is to crop the two models to contain only the overlap region (at least roughly), then compute the relative transform based on registering those, and then adding back the remainder of the two models. Maybe @neka-nat has another idea..

**Comment by neka-nat** [comment]
There is a way to use global registration.
The filterreg using fpfh is a good example.
https://github.com/neka-nat/probreg/blob/master/examples/filterreg_feature.py

**Comment by ttsesm** [comment]
> It's not easy to even match the two by looking at the data. What would be the result that you expect, I guess the CPD image with the blue model rotated 180 degree around the "up"axis? Do the two models even share an overlap region? It is a difficult setting because any registration algorithm will try to bring _all_ points close to each other. since they have a roughly identical outline that will always give a result where the two models align, and intersect, as in the CPD and FilterReg case. One thing you could try is to crop the two models to contain only the overlap region (at least roughly), then compute the relative transform based on registering those, and then adding back the remainder of the two models. Maybe @neka-nat has another idea..

Yes, one of the models should be rotated upside down. The models share the wall parts on the sides. You are right that so far what I've noticed with all the libs that i've tried is that they try to match the plane surfaces thus leading to a faulty transformation. Indeed it is not that easy case. Your idea of moving the plane surfaces is an approach, though might not be the ideal one since I would like to apply this to multiple models (couple of hundred) which are not the same thus I was looking for something more generic.

> There is a way to use global registration. The filterreg using fpfh is a good example. https://github.com/neka-nat/probreg/blob/master/examples/filterreg_feature.py

Thanks for the example. Well it seems to loop in the same issue though:

![image](https://user-images.githubusercontent.com/10189018/144395803-9c77cf94-0671-41b4-b549-6cb0452a3a01.png)

To be honest, it seems that relying just on the points might not be the best. I've noticed that open3d has a [texture based ICP implementation](http://www.open3d.org/docs/0.12.0/tutorial/pipelines/colored_pointcloud_registration.html) and considering that I can have texture available I will try to see how this works.

Thank you both anyways :-).

**Comment by drlight-code** [comment]
This is actually a quite interesting problem. You might give the texture features a try, however I would assume that those bricks are mostly of constant color and there is not too much discriminative information in the textures either. Since you have an extracted surface mesh, and not just a point set, another possible venue could be to use geometric feature descriptors that are used in shape recognition/matching/retrieval instead of, or in addition to the FPFH descriptors. A starting point could be this (kinda dated) overview paper https://dl.acm.org/doi/abs/10.5555/2381170.2381180
But even using those, it will stay a tough problem, if you have hundreds of bricks that are very similar to each other. Maybe a "bag of words" kind of pre-matching could be performed.. Anyway good luck with it!

**Comment by ttsesm** [comment]
I think the texture is gonna be helpful, if you see the images below I think there are some keypoints descriptors that could possibly be extracted and help to get the correct transformation: 

![image](https://user-images.githubusercontent.com/10189018/144426317-35a38e63-6c22-4d93-9eaf-186c7f1d5155.png)
![image](https://user-images.githubusercontent.com/10189018/144426421-6e8e618c-bca1-437c-97d2-092b876d5bcc.png)

Geometric feature descriptors are also a nice idea, and most likely I will have a better look on it.

**Comment by ttsesm** [comment]
Hi @neka-nat, @drlight-code ,

Just an update, which might be interesting for you as well as for any future reader. 

I've managed to have some nice results by using the [Teaser++](https://github.com/MIT-SPARK/TEASER-plusplus) lib. Teaser++ demands to get first some correspondences between the source and target clouds and then it tries to optimize for the final registration. Some examples can be found [here](https://github.com/MIT-SPARK/TEASER-plusplus/tree/master/examples). The example that I've tried and worked out of the box was the [teaser_python_fpfh_icp](https://github.com/MIT-SPARK/TEASER-plusplus/tree/master/examples/teaser_python_fpfh_icp). Actually the result as you see below is quite nice:

Before:
![image](https://user-images.githubusercontent.com/10189018/144872210-6c97a493-4353-48c5-bd6f-b03773ce525a.png)

Correspondences:
![image](https://user-images.githubusercontent.com/10189018/144872409-e2d7ea38-bfb2-4178-b892-d51a8f7e3d01.png)

Teaser++ result:
![image](https://user-images.githubusercontent.com/10189018/144872550-81c824bb-9497-4e7c-8846-2a1554f1df75.png)

Teaser++ result refined with ICP:
![image](https://user-images.githubusercontent.com/10189018/144872671-a6bfc71b-e257-4fb5-86c7-ee5bf4d2c3ec.png)

The correspondence points were extracted by using fpfh, but other learned 3D feature descriptors could be possible used, see e.g. [FCGF](https://github.com/chrischoy/FCGF) and [3DSmoothNet](https://github.com/zgojcic/3DSmoothNet). Personally, I didn't bother using these feature descriptors since are pretrained for indoor/outdoor scenes thus might not work properly in my case thus I might had to train them myself on my dataset (which currently is not possible). However, it might worth to give the pretrained models a try just out of curiosity. 

In any case the above solution seems to do the trick for me. It might also worth adding Teaser++ in your lib, I think it would be a nice addition.

Thanks.
