### ISSUE TITLE
FilterReg with pt2pl objective crashes

### ISSUE THREAD

**Issue by CaptainTrunky** [neka-nat/probreg#8]
Hi, @neka-nat, thanks for the awesome job you've done.

I'm conducting some experiments with Scannet dataset and I'm facing an issue with 'pt2pl' objective:

>   File "/home/captaintrunky/workspace/projects/probreg/probreg/filterreg.py", line 81, in expectation_step
>     vin = np.r_[zeros_md, self._target_normals]
>   File "/home/captaintrunky/.local/lib/python3.7/site-packages/numpy/lib/index_tricks.py", line 406, in __getitem__
>     res = self.concatenate(tuple(objs), axis=axis)
>   File "<__array_function__ internals>", line 6, in concatenate
> ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

I'm using 8f0fba65b189f15d07d00c2c9b37709bf2ebaec0 revision. 'pt2pt' does not crash, but produces pretty inaccurate results. Do you have any idea what could I try to fix it?

**Comment by neka-nat** [comment]
Calculation accuracy has improved.
#7
