### ISSUE TITLE
Unable to install probreg

### ISSUE THREAD

**Issue by gopher-confocal** [neka-nat/probreg#81]
When I attempt to install probreg, I get the following error message:

` Building wheel for probreg (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\marye\anaconda3\envs\napari-env\python.exe' 'C:\Users\marye\anaconda3\envs\napari-env\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\marye\AppData\Local\Temp\tmpvrz5cr9i'
       cwd: C:\Users\marye\AppData\Local\Temp\pip-install-j6hoj_e2\probreg_58ce6c2e327c46cd901ab1d60e90a29e
  Complete output (111 lines):
  Found Eigen version 3.3.90 in: third_party/eigen
  Found Eigen version 3.3.90 in: third_party/eigen
  Found Eigen version 3.3.90 in: third_party/eigen
  Found Eigen version 3.3.90 in: third_party/eigen
  Found Eigen version 3.3.90 in: third_party/eigen
  Found Eigen version 3.3.90 in: third_party/eigen
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\probreg
  copying probreg\bcpd.py -> build\lib.win-amd64-3.9\probreg
  copying probreg\callbacks.py -> build\lib.win-amd64-3.9\probreg
  copying probreg\cost_functions.py -> build\lib.win-amd64-3.9\probreg
  copying probreg\cpd.py -> build\lib.win-amd64-3.9\probreg
  copying probreg\cupy_utils.py -> build\lib.win-amd64-3.9\probreg
  copying probreg\features.py -> build\lib.win-amd64-3.9\probreg
  copying probreg\filterreg.py -> build\lib.win-amd64-3.9\probreg
  copying probreg\gaussian_filtering.py -> build\lib.win-amd64-3.9\probreg
  copying probreg\gauss_transform.py -> build\lib.win-amd64-3.9\probreg
  copying probreg\gmmtree.py -> build\lib.win-amd64-3.9\probreg
  copying probreg\l2dist_regs.py -> build\lib.win-amd64-3.9\probreg
  copying probreg\log.py -> build\lib.win-amd64-3.9\probreg
  copying probreg\math_utils.py -> build\lib.win-amd64-3.9\probreg
  copying probreg\se3_op.py -> build\lib.win-amd64-3.9\probreg
  copying probreg\transformation.py -> build\lib.win-amd64-3.9\probreg
  copying probreg\version.py -> build\lib.win-amd64-3.9\probreg
  copying probreg\__init__.py -> build\lib.win-amd64-3.9\probreg
  running build_ext
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  creating build\temp.win-amd64-3.9\Release\probreg
  creating build\temp.win-amd64-3.9\Release\probreg\cc
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\marye\AppData\Local\Temp\pip-build-env-gg755p05\overlay\Lib\site-packages\pybind11\include -IC:\Users\marye\AppData\Local\Temp\pip-build-env-gg755p05\overlay\Lib\site-packages\pybind11\include -Ithird_party/eigen -IC:\Users\marye\anaconda3\envs\napari-env\include -IC:\Users\marye\anaconda3\envs\napari-env\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" /EHsc /Tpprobreg/cc/ifgt.cc /Fobuild\temp.win-amd64-3.9\Release\probreg/cc/ifgt.obj /EHsc /DVERSION_INFO=\\\"0.3.4\\\"
  ifgt.cc
  probreg/cc/ifgt.cc(37): warning C4244: '*=': conversion from 'double' to 'probreg::Float', possible loss of data
  probreg/cc/ifgt.cc(45): warning C4244: 'initializing': conversion from 'const _Ty' to 'probreg::Float', possible loss of data
          with
          [
              _Ty=double
          ]
  probreg/cc/ifgt.cc(45): warning C4244: 'initializing': conversion from 'const _Ty' to 'const probreg::Float', possible loss of data
          with
          [
              _Ty=double
          ]
  probreg/cc/ifgt.cc(51): warning C4244: 'initializing': conversion from 'double' to 'probreg::Float', possible loss of data
  probreg/cc/ifgt.cc(51): warning C4244: 'initializing': conversion from 'double' to 'const probreg::Float', possible loss of data
  probreg/cc/ifgt.cc(102): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'probreg::Integer', possible loss of data
          with
          [
              Derived=Eigen::Matrix<float,-1,-1,0,-1,-1>
          ]
  probreg/cc/ifgt.cc(102): warning C4244: 'initializing': conversion from 'Eigen::EigenBase<Derived>::Index' to 'const probreg::Integer', possible loss of data
          with
          [
              Derived=Eigen::Matrix<float,-1,-1,0,-1,-1>
          ]
  probreg/cc/ifgt.cc(104): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'probreg::Integer', possible loss of data
          with
          [
              Derived=Eigen::Matrix<float,-1,-1,0,-1,-1>
          ]
  probreg/cc/ifgt.cc(109): warning C4244: 'initializing': conversion from 'const _Ty' to 'probreg::Float', possible loss of data
          with
          [
              _Ty=double
          ]
  probreg/cc/ifgt.cc(109): warning C4244: 'initializing': conversion from 'const _Ty' to 'const probreg::Float', possible loss of data
          with
          [
              _Ty=double
          ]
  probreg/cc/ifgt.cc(110): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'probreg::Integer', possible loss of data
          with
          [
              Derived=Eigen::Matrix<float,-1,-1,0,-1,-1>
          ]
  probreg/cc/ifgt.cc(111): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'probreg::Integer', possible loss of data
          with
          [
              Derived=Eigen::Matrix<float,-1,-1,0,-1,-1>
          ]
  probreg/cc/ifgt.cc(111): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'probreg::Integer', possible loss of data
          with
          [
              Derived=Eigen::Matrix<float,-1,-1,0,-1,-1>
          ]
  probreg/cc/ifgt.cc(112): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'probreg::Integer', possible loss of data
          with
          [
              Derived=Eigen::Matrix<float,-1,-1,0,-1,-1>
          ]
  probreg/cc/ifgt.cc(128): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'probreg::Integer', possible loss of data
          with
          [
              Derived=Eigen::Matrix<float,-1,-1,0,-1,-1>
          ]
  probreg/cc/ifgt.cc(142): warning C4244: 'argument': conversion from 'Eigen::EigenBase<Derived>::Index' to 'probreg::Integer', possible loss of data
          with
          [
              Derived=Eigen::Matrix<float,-1,-1,0,-1,-1>
          ]
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\marye\AppData\Local\Temp\pip-build-env-gg755p05\overlay\Lib\site-packages\pybind11\include -IC:\Users\marye\AppData\Local\Temp\pip-build-env-gg755p05\overlay\Lib\site-packages\pybind11\include -Ithird_party/eigen -IC:\Users\marye\anaconda3\envs\napari-env\include -IC:\Users\marye\anaconda3\envs\napari-env\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" /EHsc /Tpprobreg/cc/ifgt_py.cc /Fobuild\temp.win-amd64-3.9\Release\probreg/cc/ifgt_py.obj /EHsc /DVERSION_INFO=\\\"0.3.4\\\"
  ifgt_py.cc
  probreg/cc/ifgt_py.cc(14): warning C4305: 'argument': truncation from 'double' to 'probreg::Float'
  probreg/cc/ifgt_py.cc(19): error C2017: illegal escape sequence
  probreg/cc/ifgt_py.cc(19): error C2001: newline in constant
  probreg/cc/ifgt_py.cc(23): error C2143: syntax error: missing ';' before '}'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for probreg
Failed to build probreg
ERROR: Could not build wheels for probreg, which is required to install pyproject.toml-based projects

(napari-env) C:\Users\marye>`

I need to install probreg in order to install a couple of plugins for the image analysis software, napari. What are my next steps for installing probreg? I have no coding experience. I just follow instructions on the website. I invite your suggestions. Thank you. Mary

**Comment by neka-nat** [comment]
Thanks!
This has been fixed in the latest master.

**Comment by gopher-confocal** [comment]
I successfully installed probreg! Thank you!
