### ISSUE TITLE
Question about non rigid transform for  very large set of points

### ISSUE THREAD

**Issue by Alihamdy2496** [neka-nat/probreg#82]
Hi, thank you for providing this amazing library, it saved me a lot of time .

I am working on a non rigid transformation project where I need to non rigidly transform a very large set of points (in millions) to a small set of points (~1000) of course this can't be done using CPD or any algorithm directly there isn't enough memory but I want to ask you  something
I'll explain the problem clearly
in this problem I want to non rigidly transform the white points to the red points
![tell1](https://user-images.githubusercontent.com/76603283/148765118-a0324f0b-f889-4d07-a9d6-b4206c121ba6.PNG)
this large white point set is a cropped and projected depth image 
![0](https://user-images.githubusercontent.com/76603283/148765258-83763644-4648-4869-a482-f55a29de2917.png)
the depth map of this figure
![20211207_140154](https://user-images.githubusercontent.com/76603283/148765944-608e50eb-78fa-4612-9368-4b7b125d1483.jpg)
and the red point set is the output point cloud from structure from motion step
![ex1](https://user-images.githubusercontent.com/76603283/148766771-ba7b2520-556e-46b0-bf0a-c7ae88ea36ca.PNG)
since in structure from motion we don't have any information about the real depth or scale I want to correct the projected depth map to match the red points regardless of the scale of both the depth map and the output of structure from motion so its affine and non rigid transformation
the affine transformation part can be done with a simple scaling based on the distance between the image plane and the centroid of the point cloud (the output of the first image) 
but the non rigid transformation remains
when I subsample the depth map to (~5000 points) it can fit into memory and the output works fine this is the output
![tell2](https://user-images.githubusercontent.com/76603283/148767649-980ca41a-6287-4c59-a6bf-2ab7431c2043.PNG)
**my question is** 
**is there a way get the transformation information from a sample of the data and apply this transformation to all the data ?**
this is an example code to demonstrate the idea

        copy_of_depth_data= np.copy(all_depth_data)
        small_sample_of_depth_data = all_depth_data[ :: int(subsampling)]
        acpd = cpd.NonRigidCPD(small_sample_of_depth_data , use_cuda=True)
        tf_param, _, _ = acpd.registration(target_data)
        transfromed_depth_data= to_cpu(tf_param.transform(copy_of_depth_data))

**Comment by neka-nat** [comment]
Hi,
Thank you for the question,
To obtain a non-rigid transformation from a small sample and to transform a larger point cloud, it is better to use TPS transformation (Thin-plate-spline).
TPS is currently only implemented in SVR, so you need to use SVR.

```py
tf_param = l2dist_regs.registration_svr(source_sample, target, 'nonrigid')
transformed_source_large = tf_param.transform(source_large)
```

SVR does not have a cuda implementation, but it can reduce the computational cost because the number of samples can be small.

**Comment by Alihamdy2496** [comment]
thank you 👍 👍
