### ISSUE TITLE
Still "cannot import name '_math' from partially initialized module 'probreg'"

### ISSUE THREAD

**Issue by zikai1** [neka-nat/probreg#84]
Hi, I tried to run those commands, but I still have the above error, could you help me please?
I first ran the suggested commands:
**git clone https://github.com/neka-nat/probreg.git --recursive
cd  probreg
pip install -e .**
in my **remote server** using **VScode**.  Since I cannot visualize the registration results in VScode, then I downloaded the folder **probreg** in my own computer (**Windows 10+PyCharm 2020+Anaconda 4.10.3**). The **probreg** has the following building files:
![1643249307(1)](https://user-images.githubusercontent.com/37583980/151279145-ab03b8ba-67fc-4e85-a798-01d2f4170fd4.png)
It seems that there have been builded files, but when I tried to run the file **test_svr.py**, and I still have the following error:
 
![1643249463(1)](https://user-images.githubusercontent.com/37583980/151279403-4ebbe838-d2f9-473c-b41a-d4438c0ef6b0.png)

I am new in Python and PyCharm, but I really want to learn them well, hence could you please help me? Thank you very much~

**Comment by neka-nat** [comment]
Thanks!
It's a problem related to circular importing.
The following may be helpful.
https://www.pythonpool.com/python-circular-import/
