### ISSUE TITLE
Interpolate full-size displacement field where having only a few points?

### ISSUE THREAD

**Issue by tuffr5** [neka-nat/probreg#87]
Hello,
Thanks for the nice work. I am trying to interpolate the full-size displacement field (HxWxD) from a few points (N << HxWxD) that I obtained using this package, for example, CPD. I wonder if you are aware of some packages or some methods you already defined here to do the upscaling or interpolation?

Thank you so much.

**Comment by neka-nat** [comment]
Hi,
This isssue may be helpful.
https://github.com/neka-nat/probreg/issues/82

**Comment by tuffr5** [comment]
Thanks.
