### ISSUE TITLE
Conceptual question about rotation constraints

### ISSUE THREAD

**Issue by makaimann** [neka-nat/probreg#89]
Thank you for all your work on this library! This is not a true issue, but rather a conceptual question -- I hope you don't mind.

I'm interested in a problem scenario where we don't expect arbitrary rotations. Are you aware of any PSR algorithms that allow limiting constraints or regularization on the rotation/scale? So far I'm mostly familiar with CPD which (if I understand correctly) does not easily support this because of the closed-form update equations. I tried to search for this myself but couldn't find anything explicitly addressing this capability.

If you could point me to a paper to start with that might address this, I'd be very grateful!

**Comment by neka-nat** [comment]
Hi,
Thank you for contacting me!
I too am interested in registration methods with restricted rotation axis, but unfortunately I have not been able to do much research on the methods out there.
Is PSR the name of the algorithm you mentioned or something else?
If possible, could you please share the URL or something?

**Comment by makaimann** [comment]
Thanks for your response! Yes I’ve searched a bit but haven’t had any luck finding existing methods that account for restricted rotation yet. I’d be very interested if you happen to come across anything. Or maybe it’s an opportunity for new research.

By “PSR”, I meant “point set registration.” Just another term for the general problem. The main technique I’ve used so far is coherent point drift.

I’ll close this issue.
