### ISSUE TITLE
Does the FilterReg code support 2D points?

### ISSUE THREAD

**Issue by liueryun** [neka-nat/probreg#9]
As said in the title, I want a 2D version of FilterReg, how to set the parameter?

**Comment by neka-nat** [comment]
Currently, 2D Filterreg is not supported.
The kabsch algorithm needs to support 2D.

**Comment by neka-nat** [comment]
I support 2d rigid transformation for filterreg.
https://github.com/neka-nat/probreg/blob/master/examples/filterreg_rigid2d.py
