### ISSUE TITLE
Question about outliers

### ISSUE THREAD

**Issue by jangmingyu** [neka-nat/probreg#94]
First of all, thanks for sharing your great code.
I'm trying to implement a paper on "Point Set Registration: Coherent Point Drift" and I found the code and am using it. Among them I am using the affine method and I have a question about outliers here. Looking at the paper, I think that an outlier("w") is an unnecessary point or noise when matching two point clouds. We determined that performance could be improved by increasing the outliers("w") of the noisy target point cloud in e_step. However, it was confirmed that the performance deteriorated as the number of outliers increased. If anyone knows why, please comment.

**Comment by neka-nat** [comment]
Hi,
Thanks for the question.
Perhaps it is not a good idea to increase the w, since a larger w will cause the point cloud model to approach a uniform distribution.
