### ISSUE TITLE
Problems with installation of 'probreg'

### ISSUE THREAD

**Issue by almoghagag1** [neka-nat/probreg#95]
Hello,

when trying to install the package i get the following error:
Failed to build probreg
ERROR: Could not build wheels for probreg, which is required to install pyproject.toml-based projects
i'm using "pip install probreg". also tried " pip install --no-cache-dir probreg" but get the same error.
i'm using python 3.9 on windows and working inside virtual environment.
any help?
thanks

**Comment by neka-nat** [comment]
Hi,
Thanks for trying probreg!
Can you please show me all the error messages?

**Comment by almoghagag1** [comment]
Hi neka-nat,

Thank you for your responding. I get the following error:

error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for probreg
Failed to build probreg
ERROR: Could not build wheels for probreg, which is required to install pyproject.toml-based projects

**Comment by neka-nat** [comment]
Installing the build tool in the link may work.

**Comment by almoghagag1** [comment]
Thank you very much! Actually I gave already tried to install visual studio
and it works.

Best regards,

Almog Hagag.

בתאריך יום ד׳, 21 בספט׳ 2022, 01:58, מאת Shirokuma ‏<
***@***.***>:
