### ISSUE TITLE
Installing error in WIndows

### ISSUE THREAD

**Issue by YoshiiTatsuki** [neka-nat/probreg#96]
Hello and thank you for sharing a great package.

I tried to install probreg in Windows10.
But I faced the installing error.
(I copied below)
My environment is
- Windows 10
- Python 3.9
- Anaconda v22.9
- Visual Studio Comunity2017 v15.9.50
- VIsual Studio Build Tools2017 v15.9.50

I saw similar errors in the issues, but even though I tried their solution, I can't solve the problem.
my solution were
- re-install visual studio
- change python version 3.9->3.7
- edit Environment variables(add INCLUDE, LIB)
- use different ways to install; pip, GitHub 

Could you help me??

**Error message**
` "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DVERSION_INFO=0.3.6 -IC:\Users\USER\AppData\Local\Temp\pip-build-env-iqsfv6bd\overlay\Lib\site-packages\pybind11\include -IC:\Users\USER\AppData\Local\Temp\pip-build-env-iqsfv6bd\overlay\Lib\site-packages\pybind11\include -Ithird_party/eigen -IC:\Users\USER\anaconda3\envs\probreg\include -IC:\Users\USER\anaconda3\envs\probreg\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt" /EHsc /Tpprobreg/cc/ifgt_py.cc /Fobuild\temp.win-amd64-cpython-39\Release\probreg/cc/ifgt_py.obj /EHsc
      ifgt_py.cc
      C:\Users\USER\AppData\Local\Temp\pip-build-env-iqsfv6bd\overlay\Lib\site-packages\pybind11\include\pybind11/eigen.h: warning C4819: The file contains a character that cannot be represented in the current code page (950). Save the file in Unicode format to prevent data loss
      c:\users\user\anaconda3\envs\probreg\include\pyconfig.h(200): fatal error C1083: Cannot open include file: 'basetsd.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2`

**Comment by neka-nat** [comment]
Hi,
Thank you for trying my package.
The error message says that `basset.h` is missing.
You may need to install the peripheral tools by referring to the following page.
https://qiita.com/funatsufumiya/items/049fc600f13b24ea8633

**Comment by YoshiiTatsuki** [comment]
thank you for the comment!
I followed the instructions on the webpage, and it was solved!
I need to add directories in setup.py
